#+TITLE: Emacs之威: 使用Impatient Mode实时开发网站
#+URL: https://dev.to/avocadoras/the-power-of-emacs-developing-websites-in-real-time-with-impatient-mode-33fh
#+AUTHOR: lujun9972
#+TAGS: emacs-common
#+DATE: [2019年 02月 11日 星期一 15:36:45 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
你在编辑HTML或CSS文件是是否希望看浏览器呈现实时变化?Emacs为这个问题提供了一个简单的解决方案，假设你通过 =apt-get install Emacs=， =pacman -Syu Emacs= 或 =brew cask install Emacs= 安装好了Emacs.
设置Emacs之后，你需要通过MELPA安装 =impatient-mode= 包。我会给你留下一个链接，链接到我的[[https://github.com/avocadoras/.emacs.d.git][emacs配置]]，这样你就可以在不了解emacs或如何使用MELPA设置包的情况下继续学习本教程。

* 安装emacs
:PROPERTIES:
:CUSTOM_ID: install-emacs
:END:

这些步骤应该适用于任何运行Emacs的平台。Emacs预装在许多*nix发行版中，但是您可能需要首先从系统的软件包仓库库中安装Emacs GUI。

- 开启终端
- 在命令提示符中输入 =$ brew cask install emacs=， =$ pacman - syu emacs= 或 =$ apt-get install emacs=

* 在Emacs中安装impatient mode
:PROPERTIES:
:CUSTOM_ID: install-impatient-mode-in-emacs
:END:

此步骤要求你为Emacs设置MELPA，并在 =.emacs.d/= 目录中的 =initel= 文件中进行配置，然后安装 =impatient-mode= Emacs包。
好在，你可以直接将我的emacs配置复制到你的 =.emacs.d= 目录中，就不需要搞这些麻烦事了。

- 键入 =cd ~= 确保进入 =$HOME= 目录
- 运行 =$ git clone https://github.com/avocadoras/.emacs.d.git=

克隆完后, =cd= 进入存储库。

* 可选:切换到web-impatient分支
:PROPERTIES:
:CUSTOM_ID: optional-switch-to-web-impatient-branch
:END:

我的个人配置包含许多会减慢Emacs启动的包。
如果您从头开始Emacs，您将需要在Emacs中设置MELPA，然后安装Impatient Mode。
为了减少麻烦，您可以复制我的emacs配置并切换到 =web-impatient= 这个分支,该分支比我的个人配置更快Emacs。

- 在终端中提示符中输入 =$ cd .emacs.d/=, 使你进入 =.emacs.d/= 中
- 输入 =$ git checkout web-impatient= 切换到 web-impatient 分支

* 使用Emacs打开HTML文件
:PROPERTIES:
:CUSTOM_ID: tell-emacs-to-open-any-html-file
:END:

您需要使用Emacs打开文件，因此切换到文件系统中包含HTML文件的目录，或者通过键入 =$ Emacs test.html= 创建一个新文件

* 启动http服务器并为文件启动 impatient mode
:PROPERTIES:
:CUSTOM_ID: start-up-a-http-server-and-run-impatient-mode-in-your-file
:END:

在打开文件后输入 =ALT-x httpd-start= (在macOS中这应该是 =OPTION-x httpd-start= )来启动与 =impatient-mode= package自带的http服务器，然后按下键 =RETURN= 或 =ENTER=.

* 浏览localhost:8080/imp/test.html，然后在Emacs中输入html文件内容
:PROPERTIES:
:CUSTOM_ID: browse-localhost8080imptest.html-and-type-your-html-file-in-emacs
:END:

启动浏览器并转到提供文件的本地地址。地址应该是 =http://localhost:8080/imp=. 
您会看到一个已服务的文件列表。单击要呈现的文件。最后，在 =test.html= 中键入任何内容，您的浏览器将开始呈现您键入的所有内容。

* 演示
:PROPERTIES:
:CUSTOM_ID: demo
:END:

[[https://youtu.be/YSU4FF5gTiY]]
