#+TITLE: Spacemacs中的项目
#+URL: https://jaketrent.com/post/projects-in-spacemacs/
#+AUTHOR: lujun9972
#+TAGS: emacs-common
#+DATE: [2020年 01月 14日 星期二 19:30:24 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
Spacemacs上的项目非常简单，也很轻量级，非常棒.

* 没有新项目
:PROPERTIES:
:CUSTOM_ID: no-new-project
:END:

在Spacemacs中，你永远不需要进入Spacemacs菜单然后选择“新项目”。我的意思是…你的键盘很棒，按下 =Cmd-N= 就能新一个项目。
但在Spacemacs中你甚至无需这样做。你只需在文件系统的任何地方开始编辑文件即可。
你无需专门新建一个新项目、选择技术背景、勾选一堆选项、生成脚手架代码、加载项目类型支持等。编辑就是了。

* 没有项目文件
:PROPERTIES:
:CUSTOM_ID: no-project-files
:END:

许多编辑器或IDE都有项目文件的概念。它们通常位于代码目录的某个隐藏目录内。像 =.vscode= =.idea= 之类的东西。
这些文件通常存储与开发环境相关的项目配置或类似的东西。Spacemacs不会为你的代码加上这类文件。

* Git跟踪项目
:PROPERTIES:
:CUSTOM_ID: projects-tracked-by-git
:END:

无需创建新项目/编辑器相关的文件真是太棒了。然而，Spacemacs上有这么一个类似项目的东西。它实际上就是Spacemacs为你保存的曾经编辑过的本地git存储库列表。

要将某个项目添加到该列表中，只需要编辑本地git repo(带有 =.git= 子目录)中的文件即可。

* 项目命令
:PROPERTIES:
:CUSTOM_ID: project-commands
:END:

按下 =SPC p p= 调用 =helm-project-switch-project= 命令就可以检索这个项目列表，你可以选择一个最近的项目，然后编辑其中一个文件。

Once in a project, to open a file in that project, type =SPC p f= for =helm-project-find-file=.
在项目中按下 =SPC p f= 调用 =helm-project-find-file= 命令能打开该项目中的文件。

因此，项目的启动、识别和导航在Spacemacs中都非常简单和轻量级。
Spacemacs中的[[https://github.com/bbatsov/projectile][projectile]]还有许多其他有用的项目命令。

你还喜欢Spacemacs的哪些其他功能呢?
