#+TITLE: 是否值得学习Emacs GNU--陈斌的回答
#+URL: https://www.quora.com/Is-it-worth-learning-gnus-for-emacs/answer/Chen-Bin-3?srid=H9Il&share=7b1a5984 
#+AUTHOR: lujun9972
#+CATEGORY: raw
#+DATE: [2016-07-25 一 17:32]
#+OPTIONS: ^:{}

* 请问是否指的花时间学习Emacs GNUS呢?

目前我的所有文本编辑和代码编写工作都是用Emacs来完成的,我很喜欢Emacs. 但是在阅读新闻/博客/twitter/gmail时,我还是通过网页来进行的. 我曾经稍微试用过一下子gnus, 但是在我花时间深入学习gnus之前,我想了解下我的回报有哪些---GNUS看起来相当复杂而且它的价值主张也不是很清晰.

* 陈斌的回答

值得花时间, 你可以看看我写得[[http://blog.binchen.org/?p=403][Gnus玩转Gmail实战]]指南

使用Gnus的原因有:
=================
1. 发送email不再困难,在任何地方按下 =C-x m= 就能发送一封新邮件
2. 将所有邮件标记为已读的操作要比在Gmail web UI上操作更来得方便
3. 添加附件和转发多个email真的很方便
4. 当使用email时可以借力于其他的emacs插件

请注意以下几点:
=========
1. 我并不阅读新闻组和邮件列表
2. 有时候我也会用Gmail web UI
3. 通过整合w3m,Gnus也支持阅读html邮件
4. 通过整合org-mode 和 org-mime这两个插件,你可以编写html邮件(当在编写包含html表格的email时特别棒).

使用Gnus的关键点
==================
这个部分很重要,因为即使你已经被我说服了使用Gnus. 但是尝试过一次后,你依然很可能会放弃.

Gnus默认情况下,在某些情况下会自动隐藏一些电子邮件和新闻组,这简直是自作聪明. 大多数人无法忍受Gnus是因为他们不知道为什么有些邮件被丢失掉了.

例如. 你阅读完了所有的邮件后就没有再管它们了. 然后一个小时后,你的老板告诉你,其中有一封邮件特别重要,他要和你一起讨论一下这封邮件. 你打开Gnus,结果发现 =INBOX= folder不见了!
Gnus默认会隐藏不包含未读邮件的folder! 随便一提,Gmail其实也有类似的功能,但是默认是关闭的.

如果你带着疑问来阅读manual(我就是这么做的,我花了整整5个小时来阅读manual), 你会发现它的manual有点难以理解.

不管怎么说,我费了老大劲总算是读完了manual了,现在我已经知道该怎么做了.

关键点在于告诉gnus *显示出所有的东西*:
1. 看我上面指南,上面有详细的配置信息
2. 当你打开没有未读邮件的 =INBOX= folder时,通过 =C-u <RET>= 打开而不要直接按 =<RET>= 打开,这样才能看到所有的电子邮件.

Tips
====
1. 当没填都要编写类似内容的邮件时(例如,回复工作日程),yasnippet很有帮助.
2. 按下 =c= 就能将inbox中的所有邮件都标记会已读,这真是太方便了(相对来说,Gmail的界面就差了点)
3. 搜索,过滤(在gnus中,这些动作统称为限定(limit))电子邮件的操作令人满意 (搜索没有gmail那么方便,但是过滤要比gmail方便多了)
4. 可以安装一个名为 =popfile= 的软件来为你的邮件分类,它比google自己的分类器要好太多了(不管是在过滤规则上,还是自动加标签上都是这样)
5. 在Gnus为email添加附件很有效率(只需要1,2秒就能搞定)
6. 转发邮件或者将email作为附件(attach email)都很容易
7. 你可以使用另一个叫做 =davmail= 的软件来从outlook exhange server中收取邮件(请使用pop3协议而不是imap协议,因为gnus有些bug),当然若你使用POP3协议,别忘了在server端留一份邮件的拷贝.
8. 阅读html邮件也很容易,使用emacs-w3m就行
9. 使用org-mine编写html邮件要比在其他软件中更有效率,尤其要创建html表格时,效率快了十倍有余.

若你需要详细的配置信息,请查看[[http://github.com/redguardtoo/emacs.d][redguardtoo/emacs.d]]
