#+TITLE: An Emacs Library for frictionless Blogging
#+URL: https://write.as/dani/an-emacs-library-for-frictionless-blogging
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 12月 24日 星期一 17:31:58 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

*TLDR: Blog post you are about to read was written in Org Mode and instantly published to this website with one function call. Code [[https://github.com/dangom/writefreely.el][on GitHub]].*
*TLDR:您将要阅读的博客文章是在Org模式下编写的，并通过一个函数调用立即发布到本网站。GitHub上代码[[https://github.com/dangom/writefreely.el] []]。*

* Library idea
*库的想法
:PROPERTIES:
属性:
:CUSTOM_ID: library-idea
:CUSTOM_ID library-idea
:END:
结束:

There is this thing called the Fediverse. [[https://en.wikipedia.org/wiki/Fediverse][According to Wikipedia]], Fediverse (a portmanteau of “federation” and “universe”) is the ensemble of federated servers that are used for web publishing (i.e. social networking, microblogging or websites) and file hosting. I came across one of such federated microblogging platforms not long ago, [[https://writefreely.org][writefreely]], and it's flagship instance [[https://write.as][write.as]] . It offers a distraction-free experience, no adds, privacy by default, and users can even write using markdown. I guess the time has finally come to start a blog. Being an Emacs user, though, I figured that before actually starting a blog or doing any meaningful writing, I should write an Elisp library that allows posting to said blogging platform. My goal is to write posts in Org Mode, have them exported to markdown using =ox-md.el=, and directly pushed to the Fediverse. Luckily, [[https://write.as][write.as]] offers an easy to use API. Users can write anonymous blogposts by simply submitting POST requests with a “title” and a “body” to their RESTful API endpoint. With an authorization token in the request header, the blogpost is automatically associated to an user account.
有一种东西叫做fediversity。[[https://en.wikipedia.org/wiki/fe不同点][根据维基百科]]，fe不同点(“联邦”和“宇宙”的合成词)是用于网络发布(即社交网络、微博客或网站)和文件托管的联邦服务器的集合。不久前，我偶然发现了这样一个联合微博平台，它的旗舰实例是[[https://writefreely.org][writefreely]]。]]。它提供了一个无干扰的体验，没有添加，默认情况下是隐私的，用户甚至可以使用markdown进行编写。我想是时候开始写博客了。但是，作为Emacs用户，我认为在实际开始博客或进行任何有意义的写作之前，我应该编写一个Elisp库，允许在上述博客平台上发布。我的目标是在Org模式下写文章，使用=ox-md导出到markdown。el=，直接推到fe。幸运的是,[[https://write.as][写。提供了一个易于使用的API。用户可以通过向RESTful API端点提交带有“标题”和“正文”的POST请求来撰写匿名博客文章。通过请求头中的授权令牌，blogpost将自动关联到用户帐户。

After some minutes of thinking I figured my library would have to support the following functionality:
经过几分钟的思考，我认为我的图书馆将不得不支持以下功能:

1. Extract “title” and “body” from an Org document (exported to markdown)
1. 从一个Org文档中提取“title”和“body”(导出到markdown)
2. Submit a POST request to the write.as API endpoint
2. 向写提交一个POST请求。作为API端点
3. Get the post id and access token from the request response.
3.从请求响应中获取post id和访问令牌。
4. Store this information somewhere meaningful for later use.
4. 将此信息存储在有意义的地方供以后使用。

I never did anything like that with Elisp. In fact, I never did much at all with Elisp, so this library would be the perfect opportunity to start learning.
我从来没对Elisp做过这样的事。事实上，我从来没有做很多关于Elisp，所以这个库将是一个开始学习的完美机会。

** Extracting information from Org document
**从Org文档中提取信息
:PROPERTIES:
属性:
:CUSTOM_ID: extracting-information-from-org-document
:CUSTOM_ID extracting-information-from-org-document
:END:
结束:

The first one is easy. The title of an Org document is specified in =#+TITLE=, so I just need a programatic way to read the property. The body is all the content in the Org-to-markdown export.
第一个很简单。Org文档的标题是在=#+ title =中指定的，所以我只需要用一种编程方式来读取属性。body是Org-to-markdown导出中的所有内容。

To get the title, I found the following function in the Emacs devel [[http://lists.gnu.org/archive/html/emacs-orgmode/2018-11/msg00133.html][mailing list]]. Coincidently, it was posted about a week ago.
为了获得标题，我在Emacs devel [[http://lists.gnu.org/archive/html/emacs-orgmode/2018-11/msg00133.html][邮件列表]]中找到了以下函数。巧合的是，它是在一周前发布的。

#+BEGIN_EXAMPLE
(defun get-orgmode-keyword (key)
(org-element-map (org-element-parse-buffer) 'keyword
(lambda (k)
(when (string= key (org-element-property :key k))
(org-element-property :value k)))
nil t))
#+END_EXAMPLE

And so to get the title all we have to do is:
为了得到标题，我们需要做的就是:

#+BEGIN_EXAMPLE
(get-orgmode-keyword "TITLE")
#+END_EXAMPLE

Getting the md export is also trivial. All we need to do is export the file to a temporary buffer as mardown, then get a string between =point-min= and =point-max= and save it to a body variable.
获得md导出也很简单。我们所需要做的就是将文件作为mardown导出到一个临时缓冲区中，然后获取一个介于=point-min=和=point-max=之间的字符串，并将其保存到一个body变量中。

#+BEGIN_EXAMPLE
(defun writefreely-org-to-md-string ()
(let ((org-buffer (current-buffer))
(md-buffer (org-md-export-as-markdown)))
(let ((md-string
(with-current-buffer md-buffer
(buffer-substring (point-min) (point-max)))))
(set-buffer org-buffer)
(kill-buffer md-buffer)
md-string)))
#+END_EXAMPLE

** Submitting a POST request
**提交POST请求
:PROPERTIES:
属性:
:CUSTOM_ID: submitting-a-post-request
:CUSTOM_ID submitting-a-post-request
:END:
结束:

This one is also simple. I know nothing about RESTful APIs and asynchronous requests, yet the examples in the [[https://github.com/tkf/emacs-request][request.el]] library are enough to come up with the following:
这个也很简单。我对RESTful api和异步请求一无所知，但[[https://github.com/tkf/emacs-request][request.el]]库中的示例足以得出以下结果:

#+BEGIN_EXAMPLE
(defvar writefreely-api-endpoint "https://write.as/api/posts"
"URL of the writefreely instance API endpoint")

(defun writefreely-post-publish-request (title body)
"post title and body. Return parsed JSON response"
(request-response-data
(request
writefreely-api-endpoint
:type "POST"
:parser #'json-read
:data (json-encode
`(("title" . ,title)
("body" . ,body)))
:headers '(("Content-Type" . "application/json"))
:sync t
:error (function* (lambda (&key error-thrown &allow-other-keys&rest _)
(message "Got error: %S" error-thrown))))))
#+END_EXAMPLE

What this function is doing is simple: it's submitting a request using =request=, waiting for the response (see the =sync= keyword set to =t=) and then reading and returning it with =request-response-data=. Note that I'm using =:sync t= because I haven't learned yet how to deal with async, and the request takes less than a second anyway (and I'll probably only submit a blogpost every now and then). For now, what we have is enough for us to submit anonymous posts.
这个函数所做的事情很简单:它使用=request=提交请求，等待响应(参见=sync=关键字设置为=t=)，然后读取并返回=request-response-data=。注意，我使用的是=:sync t=，因为我还没有学习如何处理异步，而且请求只需要不到一秒钟的时间(我可能只是偶尔提交一篇博客文章)。目前，我们所拥有的足够我们提交匿名帖子。

** Getting the ID and Token from the response
**从响应获取ID和令牌
:PROPERTIES:
属性:
:CUSTOM_ID: getting-the-id-and-token-from-the-response
:CUSTOM_ID getting-the-id-and-token-from-the-response
:END:
结束:

A response, after parsed, will look like the following:
解析后的响应如下:

((code . 201)
((代码。201)
(data
(日期
(id . “1234567890123”)
(id。“1234567890123”)
(slug)
(料)
(token . “uffVIr18ygX2kR7e3vISjVv9o8ukLlmi”)
(令牌。“uffVIr18ygX2kR7e3vISjVv9o8ukLlmi”)
(appearance . “norm”)
(外观。“规范”)
(language . “”)
(语言。" ")
(rtl . :json-false)
(rtl。:json-false)
(created . “2018-11-16T21:51:58Z”)
(创建。“2018 - 11 - 16 t21:51:58z”)
(updated . “2018-11-16T21:51:58Z”)
(更新。“2018 - 11 - 16 t21:51:58z”)
(title . “title”)
(标题。“标题”)
(body . “body”)
(身体。“身体”)
(tags .
(明天。
[])
(views . 0)))
(观点。0)))

The 13-digit post id is what tells us where to find the post in the web. If id is the one in the example above, then the url of a post is given by =https://write.as/1234567890123=, or =https://write.as/1234567890123.md= (note the .md extension) for displaying it with markdown syntax. The 32-character token is only required if we want to either update or claim an anonymous post.
13位的帖子id告诉我们在网络上的什么地方可以找到帖子。如果id是上面示例中的id，则post的url由=https://write提供。/ 1234567890123 =,= https://write.as/1234567890123。md=(注意.md扩展名)，用于用markdown语法显示它。只有在需要更新或声明匿名帖子时，才需要32个字符的令牌。

To get the =id= and =token= from the response, the following is sufficient.
要从响应中获取=id=和=token=，以下操作就足够了。

#+BEGIN_EXAMPLE
(assoc-default 'id (assoc 'data writefreely-response))
(assoc-default 'token (assoc 'data writefreely-response))
#+END_EXAMPLE

** Storing writefreely data somewhere meaningful
**将写数据存储在有意义的地方
:PROPERTIES:
属性:
:CUSTOM_ID: storing-writefreely-data-somewhere-meaningful
:CUSTOM_ID storing-writefreely-data-somewhere-meaningful
:END:
结束:

We could have a directory where we save all posts. Or alternatively a cache file that stores information about all posts we submit. But I figured the simplest thing to do is to store the ID and token information in the Org document itself. The advantages of this approach is that we can then update posts later, by checking if the document already has an ID and token, and we don't have to clutter our filesystem with extra stuff. Additionally, we can get an URL in the Org document to visit the post online.
我们可以有一个保存所有帖子的目录。或者一个缓存文件，存储我们提交的所有帖子的信息。但我认为最简单的方法是将ID和令牌信息存储在Org文档本身中。这种方法的优点是，我们可以稍后更新帖子，方法是检查文档是否已经有了ID和令牌，这样我们就不必用额外的东西把文件系统弄得乱七八糟。另外，我们可以在Org文档中获得一个URL来在线访问post。

I decided to store the id and token, and the url in file-local variables. That's also easy to accomplish using one of two Emacs built-in functions: =add-file-local-variable= or =add-file-local-variable-prop-line=.
我决定将id和令牌以及url存储在文件本地变量中。使用两个Emacs内置函数中的一个也很容易实现:=add-file-local-variable=或=add-file-local-variable-prop-line=。

#+BEGIN_EXAMPLE
(add-file-local-variable 'writefreely-id "1234567890123")
(add-file-local-variable 'writefreely-token "uffVIr18ygX2kR7e3vISjVv9o8ukLlmi")
#+END_EXAMPLE

** Putting it all together
把它们放在一起
:PROPERTIES:
属性:
:CUSTOM_ID: putting-it-all-together
:CUSTOM_ID:把它们放在一起
:END:
结束:

Now we write an interactive function that gets the title and the body of a document, sends them to write.as using a POST request, and stores the post-id and post-token in the current file.
现在，我们编写一个交互式函数，它获取文档的标题和正文，并将它们发送给write。与使用POST请求一样，并将POST -id和POST -token存储在当前文件中。

#+BEGIN_EXAMPLE
(defun writefreely-publish-buffer ()
"Publish the current Org buffer to a writefreely instance."
(let* ((title (writefreely-get-orgmode-keyword "TITLE"))
(body (writefreely-org-to-md-string))
;; POST the blogpost with title and body
(response (writefreely-post-publish-request title body))
;; Get the id and token from the response
(post-id (assoc-default 'id (assoc 'data response)))
(post-token (assoc-default 'token (assoc 'data response))))
;; Use setq-local as well because otherwise the local variables won't be
;; evaluated until we reopen the file.
(setq-local writefreely-post-id post-id)
(add-file-local-variable 'writefreely-post-id post-id)
(setq-local writefreely-post-token post-token)
(add-file-local-variable 'writefreely-post-token post-token)))
#+END_EXAMPLE

* Next steps
*下一步
:PROPERTIES:
属性:
:CUSTOM_ID: next-steps
:CUSTOM_ID:下一步
:END:
结束:

[[https://github.com/dangom/writefreely.el][WriteFreely.el]] is available on GitHub. You can find install instructions on the README file. For now, what I'd like to add are the following features:
[[https://github.com/dangom/writefreely.el]]可在GitHub上下载。你可以在自述文件中找到安装说明。现在，我想添加以下功能:

- Get a confirmation from the user before publishing.
-发布前得到用户的确认。
- Update a post, if the Org file already contains writefreely local variables.
更新一篇文章，如果组织文件已经包含了可写的局部变量。
- A function to open the post online.
-一个功能，打开网上的职位。
- Allow posting as authenticated user.
-允许张贴作为认证用户。

This is done by setting the variable =writefreely-auth-token= to an authentication token. In order to not keep it hanging around in the open, you can encrypt and load it on startup as described [[https://www.masteringemacs.org/article/keeping-secrets-in-emacs-gnupg-auth-sources][in this post]] from Mastering Emacs.
这是通过将变量= writefrie - aui -token=设置为身份验证令牌来实现的。为了不让它挂在开放，你可以加密和加载它在启动时所描述的[[https://www.masteringemacs.org/article/keeping-secrets-inemacs-gnups-au-sources][在这篇文章]]从掌握Emacs。

- [ ] Delete a post.
-[]删除一个帖子。
- [ ] Automatically upload images from the filesystem.
-[]从文件系统自动上传图像。
- [ ] Retrieve post into an Org file.
-[]检索职位到一个组织文件。
- Figure out how to make Ox-md export code as code, not text.
-找出如何使Ox-md出口代码作为代码，而不是文本。

Now depend on ox-gfm instead of ox-md.
现在要依赖ox-gfm而不是ox-md。

* Things I wish to see in write.as
我希望看到的东西写下来
:PROPERTIES:
属性:
:CUSTOM_ID: things-i-wish-to-see-in-write-as
:CUSTOM_ID things-i-wish-to-see-in-write-as
:END:
结束:

Proper syntax highlighting for different languages would be awesome.
正确的语法高亮显示对于不同的语言来说是非常棒的。
