#+TITLE: Emacsclient on Windows
#+URL: https://scripter.co/emacsclient-on-windows/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 06月 06日 星期三 21:35:55 CST]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
Using emacsclient instead of the emacs binary is a very useful technique to prevent loading emacs from scratch each time you open a new file. That technique is useful on Windows too. But for this to work on Windows, we need some more elisp and Windows environment variable configuration than just the below code,
使用emacsclient而不是emacs二进制文件是一种非常有用的技术，可以防止每次打开新文件时从头开始加载emacs。这项技术在Windows上也很有用。但是要在Windows上运行，我们需要更多的elisp和Windows环境变量配置，而不仅仅是下面的代码，

#+BEGIN_EXAMPLE
(require 'server)
;; Start a server if (server-running-p) does not return t (e.g. if it
;; returns nil or :other)
(or (eq (server-running-p) t)
(server-start))
#+END_EXAMPLE

* Setup in elisp [[#setup-in-elisp][#]]
:PROPERTIES:
:CUSTOM_ID: setup-in-elisp
:END:

** Use TCP sockets [[#use-tcp-sockets][#]]
:PROPERTIES:
:CUSTOM_ID: use-tcp-sockets
:END:

I do not understand what this means, but you need to use TCP sockets instead of local sockets for the server to run on Windows. By default the value of =server-use-tcp= is =nil=. So for Windows, we need this,
我不明白这意味着什么，但你需要使用TCP套接字，而不是本地套接字的服务器上运行的Windows。默认情况下=server-use-tcp= is =nil=。对于Windows，我们需要这个，

#+BEGIN_EXAMPLE
(when (equal window-system 'w32)
(setq server-use-tcp t))
#+END_EXAMPLE

** Uniquify the server authentication directory [[#uniquify-the-server-authentication-directory][#]]
**统一服务器认证目录[[# Uniquify -the-server- authentic- directory][#]]
:PROPERTIES:
属性:
:CUSTOM_ID: uniquify-the-server-authentication-directory
:CUSTOM_ID uniquify-the-server-authentication-directory
:END:
结束:

When =server-use-tcp= is a non-nil value, the =server-auth-dir= is used to store the server authentication files. It is not unusual for me to have emacs running on two different machines (possibly different versions of emacs on the same machine too in rare occassions) sharing the same =~/.emacs.d/= via Dropbox. So I uniquify the =server-auth-dir=.
当=server-use-tcp=是非空值时，=server-auth-dir=用于存储服务器身份验证文件。对于我来说，在两台不同的机器上运行相同的emacs是很正常的(在罕见的情况下可能在同一台机器上运行不同版本的emacs)，共享相同的=~/.emacs。通过Dropbox d / =。所以我统一了=server-auth-dir=。

#+BEGIN_EXAMPLE
;; Below needs to be set before you require 'server
(setq server-auth-dir
(let ((dir (concat user-emacs-directory
"server_" (format "%s_%s"
emacs-major-version
emacs-minor-version)
"_" (system-name) ; Use the var `system-name' directly
; if using emacs older than 25.1.
"/")))
(make-directory dir :parents)
dir))
#+END_EXAMPLE

So, if am running emacs 25.1, and if my Windows machine name is =FOO=, the value of =server-auth-dir= will be set to =~/.emacs.d/server_25_1_FOO/=.
因此，如果我正在运行emacs 25.1，并且我的Windows机器名是=FOO=，那么=server- auc -dir=的值将被设置为=~/.emacs.d/server_25_1_FOO/=。

** Prevent ‘server is unsafe' errors [[#prevent-server-is-unsafe-errors][#]]
**防止“服务器不安全”错误[[# Prevent -server-is-unsafe-errors][#]]
:PROPERTIES:
属性:
:CUSTOM_ID: prevent-server-is-unsafe-errors
:CUSTOM_ID prevent-server-is-unsafe-errors
:END:
结束:

I also had to put the below hack in order for the server to start on Windows.
为了让服务器在Windows上启动，我还不得不使用下面的技巧。

#+BEGIN_EXAMPLE
(with-eval-after-load 'server
(when (equal window-system 'w32)
;; Suppress error "directory ~/.emacs.d/server is unsafe". It is needed
;; needed for the server to start on Windows.
(defun server-ensure-safe-dir (dir) "Noop" t)))
#+END_EXAMPLE

* Windows环境变量[[# Windows -environment-variables][#]]
:PROPERTIES:
属性:
:CUSTOM_ID: windows-environment-variables
:CUSTOM_ID windows-environment-variables
:END:
结束:

You will need to set =EMACS_SERVER_FILE= and =HOME= environment variables in Windows. I came up with the below steps that work on Windows 7.
您需要在Windows中设置=EMACS_SERVER_FILE=和=HOME=环境变量。我提出了以下适用于Windows 7的步骤。

- Click on Start > Control Panel.
-点击启动>控制面板。
- Search for environment in the search field.
-在搜索字段中搜索环境。
- Click on Edit environment variables for your account.
-点击编辑环境变量为您的帐户。
- Click on New under User variables for ...
-点击用户变量下的新…
- Enter =EMACS_SERVER_FILE= in the Variable name field and appropriate value in the Variable value field to match the value set in =server-auth-dir=, appended by =server=.
-在变量名字段中输入=EMACS_SERVER_FILE=，并在变量值字段中输入适当的值，以匹配由=server=附加的=server-auth-dir=中设置的值。

- My =server-auth-dir= value is =~/.emacs.d/server_25_1_FOO/=. So I have set Variable value to =C:UsersKModiDropboxhome.emacs.dserver_25_1_FOOserver=. Note the use of =/= instead of ==.
- My =server-auth-dir= value is =~/.emacs.d/server_25_1_FOO/=。因此我将变量值设置为=C:UsersKModiDropboxhome.emacs.dserver_25_1_FOOserver=。注意使用=/=代替==。
- Also I have set my user environment variable =HOME= in Windows to =C:UsersKModiDropboxhome= using the same steps as above.
-我还设置了我的用户环境变量=HOME= in Windows =C:UsersKModiDropboxhome=使用相同的步骤如上。

- Hit OK to save your environment variable setup.
-点击确定保存环境变量设置。

* Start the server [[#start-the-server][#]]
*启动服务器[[#启动服务器][#]]
:PROPERTIES:
属性:
:CUSTOM_ID: start-the-server
:CUSTOM_ID:启动服务器
:END:
结束:

And then you need to have the below snippet that starts the server when you start emacs.
然后需要下面的代码片段在启动emacs时启动服务器。

#+BEGIN_EXAMPLE
(require 'server)
;; Start a server if (server-running-p) does not return t (e.g. if it
;; returns nil or :other)
(or (eq (server-running-p) t)
(server-start))
#+END_EXAMPLE

* Using the emacsclient [[#using-the-emacsclient][#]]
*使用emacsclient[[#使用-the-emacsclient][#]]
:PROPERTIES:
属性:
:CUSTOM_ID: using-the-emacsclient
:CUSTOM_ID using-the-emacsclient
:END:
结束:

1. Start emacs using the =runemacs.exe= executable for the first time on starting Windows.
1. 使用=runemacs启动emacs。exe=第一次启动Windows时的可执行文件。
2. Use the =emacsclientw.exe= executable after that.
2. 使用= emacsclientw。exe=可执行文件。

To makes things easy, I add =runemacs.exe= Shortcut to All Programs > Startup. So emacs starts automatically each time I boot Windows.
为了使事情变得简单，我添加=runemacs。exe=所有程序>启动的快捷方式。所以每次我启动Windows时，emacs都会自动启动。

If you need to always open certain files in emacs using emacsclient, - Shift + Right-click on that file. - Select Open with. - Click Select default program and choose the =emacsclientw.exe= executable.
如果您需要使用emacsclient在emacs中打开某些文件，可以使用- Shift +右键单击该文件。-选择Open with。-点击选择默认程序并选择=emacsclientw。exe可执行。

- You can find my full setup related to emacs server setup [[https://github.com/kaushalmodi/.emacs.d/blob/6c7b77af6ea39fd6e016a873fad763a712547223/setup-files/setup-server.el][here]].
-你可以找到我的完整安装相关的emacs服务器设置[[https://github.com/kaushalmodi/.emacs.d/blob/6c7b77af6ea39fd6e016a873fad763a712547223/setup-files/setup-server.el][这里]]。
- This has been tested to work on emacs 25.1 on the [[https://ftp.gnu.org/gnu/emacs/windows/][official emacs Windows]] as well as [[https://github.com/zklhp/emacs-w64/releases][emacs-w64]] builds.
-这已经过测试，以工作在emacs 25.1上的[[https://ftp.gnu.org/gnu/emacs/windows/][官方emacs的Windows]]，以及[[https://github.com/zklhp/emacs-w64/releases][emacs-w64]]构建。
