#+TITLE: eww's awesome isearch support just blew my mind : emacs
#+URL: https://www.reddit.com/r/emacs/comments/9oi1e3/ewws_awesome_isearch_support_just_blew_my_mind/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 10月 25日 星期四 11:40:14 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
What I learned:

If a web page contains navigation 'link' elements with 'rel' attributes for "next", "prev", "up", or "start" (plus a few supported synonyms), then you can navigate in =eww= by typing =n=ext, =p=revious, =u=p, =t=op; just like you do in the =info= reader. So far, so nice.

The eye-opener was when I used isearch in a page, ran out of matches in the buffer, typed =C-s= again to wrap around, and unexpectedly found myself looking at the next page containing a match, in that sequence of web pages.

i.e. This is like isearch in =info= -- but working on web pages. eww keeps following those "next" links until it finds another page with a match for the search term. (Internally this is using misearch.el, so the amount of code needed in eww turns out to be absolutely minimal. Very cool.)

For locally-hosted HTML documentation in particular (which eww is perfect for, and for which this behaviour will be fast), this feature is absolutely superb.

If you're using eww for documentation, and the HTML doesn't contain navigation 'link' elements, this is reason enough to ask the maintainers to add them. (And if you're not using eww for this, it's probably reason enough to start.)
