#+TITLE: org-mode in Your Pocket
#+URL: https://nakkaya.com/2010/03/19/org-mode-in-your-pocket-setting-up-mobileorg/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 09月 12日 星期三 19:02:19 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

[[http://mobileorg.ncogni.to][MobileOrg]] is an iPhone application that lets you view, modify org files on the go. Its a great application but documentation is scarce and a bit confusing. This post documents the steps required to configure org-mode so it can sync with MobileOrg.
[[http://mobileorg.ncogni。[MobileOrg]]是一个iPhone应用程序，让你查看，修改组织文件的行动。这是一个很好的应用程序，但是文档很少，而且有点混乱。这篇文章记录了配置组织模式所需的步骤，这样它就可以与MobileOrg同步。

By default org-mode looks into the "~/org/" folder for your org files if you keep them somewhere else set org-directory variable to point to it,
默认的组织模式是查看你的组织文件的“~/org/”文件夹，如果你把它们放在其他地方，设置组织目录变量指向它，

#+BEGIN_EXAMPLE
(setq org-directory "~/Documents/org/")
(setq org-mobile-inbox-for-pull "~/Documents/org/from-mobile.org")
#+END_EXAMPLE

MobileOrg uses WebDav to synchronize your files, if you mount your WebDav as a disk, you need to set org-mobile-directory to point to it, alternatively you can use org-mobile push/pull hooks and use scp instead.
MobileOrg使用WebDav来同步你的文件，如果你把你的WebDav作为一个磁盘挂载，你需要设置org-mobile-directory指向它，或者你可以使用org-mobile push/pull钩子和使用scp代替。

#+BEGIN_EXAMPLE
(setq org-mobile-directory "/Volumes/nakkaya.com/org/")
#+END_EXAMPLE

By default no files are staged to WebDav, you need to set org-mobile-files to the list of files you want to have access on the iPhone,
在默认情况下，没有文件被暂存到WebDav，你需要将org-mobile-files设置为你想在iPhone上访问的文件列表，

#+BEGIN_EXAMPLE
(setq org-mobile-files (quote ("gtd.org")))
#+END_EXAMPLE

When you sync your org files org-mobile will add a property drawer to your files, if you want to get rid of it you can use,
当你同步你的org文件时，org-mobile会给你的文件添加一个属性抽屉，如果你想摆脱它，你可以使用，

#+BEGIN_EXAMPLE
(setq org-mobile-force-id-on-agenda-items nil)
#+END_EXAMPLE

but beware that if you have file structure such as,
但是要注意，如果你有像这样的文件结构，

#+BEGIN_EXAMPLE
0_sync_master.sh 1_add_new_article_manual.sh 1_add_new_article_newspaper.sh 2_start_translating.sh 3_continue_the_work.sh 4_finish.sh 5_pause.sh base.sh parse_url_by_manual.sh parse_url_by_newspaper.py parse_url_by_newspaper.sh project.cfg reformat.sh texput.log urls_checker.sh Task
0_sync_master.sh 1_add_new_article_manual.sh 1_add_new_article_newspaper.sh 2_start_translating.sh 3_continue_the_work.sh 4_finish.sh 5_pause.sh base.sh parse_url_by_manual.sh parse_url_by_newspaper.py parse_url_by_newspaper.sh project.cfg reformat.sh texput.log urls_checker.sh SubTask
0_sync_master.sh 1_add_new_article_manual.sh 1_add_new_article_newspaper.sh 2_start_translating.sh 3_continue_the_work.sh 4_finish.sh 5_pause.sh base.sh parse_url_by_manual.sh parse_url_by_newspaper.py parse_url_by_newspaper.sh project.cfg reformat.sh texput.log urls_checker.sh Task
0_sync_master.sh 1_add_new_article_manual.sh 1_add_new_article_newspaper.sh 2_start_translating.sh 3_continue_the_work.sh 4_finish.sh 5_pause.sh base.sh parse_url_by_manual.sh parse_url_by_newspaper.py parse_url_by_newspaper.sh project.cfg reformat.sh texput.log urls_checker.sh SubTask
#+END_EXAMPLE

and you edit one of the subtasks org-mobile will have no way to determine which one to edit, other than that you will be safe. As for agendas only your custom agenda views are synchronized, I also suggest you use org-agenda-show-all-dates and set it to nil, so it filters empty days, it makes viewing agendas easier.
如果你编辑其中一个子任务，org-mobile将无法确定编辑哪一个子任务，除非你是安全的。至于议程只有您的自定义议程视图是同步的，我还建议您使用org- -show-all-date并将其设置为nil，以便过滤空天，使查看议程更容易。

#+BEGIN_EXAMPLE
(setq org-agenda-custom-commands
'(("w" todo "TODO")
("h" agenda "" ((org-agenda-show-all-dates nil)))
("W" agenda "" ((org-agenda-ndays 21)
(org-agenda-show-all-dates nil)))
("A" agenda ""
((org-agenda-ndays 1)
(org-agenda-overriding-header "Today")))))
#+END_EXAMPLE
