#+TITLE: Robust Notes with Embedded Code
#+URL: https://www.arcadianvisions.com/blog/2018/org-nix-direnv.html
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 09月 20日 星期四 22:28:47 CST]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
Emacs's org-mode has great [[https://orgmode.org/manual/Working-with-source-code.html#Working-with-source-code][facilities for working with source code]], often referred to by the name *Org Babel*. A simple use is having source code from various languages embedded in a single text file that is otherwise occupied with talking about that code.
Emacs的组织模式有很好的[[https://orgmode.org/manual/Working-with-source-code.html# working -with-source-code][处理源代码的工具]]，通常被称为*Org Babel*。一个简单的用法是将来自不同语言的源代码嵌入到一个文本文件中，否则这个文本文件将被用来讨论这些代码。

There are myriad ways one can use this functionality, but here let's focus on just one: short code demonstrations. While working on a large project, you encounter a technique or library whose usage is not obvious to you today. This means that even as you figure out how to solve your problem today, when you come back to your code a year from now, your solution may again not be obvious to future-you who has forgotten the hard-won lessons of today-you. What we want to record in our notes is a set of example programs we wish we found when writing today's code.
有无数种方法可以使用这个功能，但是这里我们只关注一种:简短的代码演示。在处理大型项目时，您会遇到一种技术或库，其用法在今天并不明显。这意味着，即使您现在已经找到了解决问题的方法，但当您一年后重新回到您的代码时，您的解决方案可能对将来(您已经忘记了今天来之不易的教训)仍然不是很明显。我们想在笔记中记录的是一组示例程序，我们希望在编写今天的代码时能够找到它们。

Now, the tricky part in finding the perfect example for whatever problem you're facing is that the author of the perfect example must be using the /exact same/ tools that you are. It's hardly a perfect example if the author uses a different version of some software library at the center of what you're trying to do! We want the example to exactly reproduce the environment in which we are building our larger project. No surprises, please.
现在，为您所面临的任何问题寻找完美示例的棘手部分是，完美示例的作者必须使用与您相同的/工具。如果作者在你要做的事情的中心使用了某个软件库的不同版本，这并不是一个完美的例子!我们希望这个示例能够准确地重现我们构建大型项目时所处的环境。请不要惊讶。

Reproducible development environments just happen to be the forte of the [[https://nixos.org/nix/][nix package manager]]. Here we can pin down precise versions of the source code of each of our tools, that of their dependencies, that of their dependencies' dependencies, and so on all the way up stream.
可复制的开发环境恰好是[[https://nixos.org/nix/][nix包管理器]]的长处。在这里，我们可以确定每个工具的源代码的精确版本，它们的依赖项，它们的依赖项的依赖项，等等。

Coming back to where we started: we want to record in our =org-mode= notes example programs that clearly demonstrate a technique or API exactly as it is used in our larger project. We thus want Emacs to know how to evaluate source code blocks in the context of the project the notes are related to.
回到我们开始的地方:我们希望在我们的=org-mode= notes示例程序中记录清楚地演示一种技术或API，就像在我们的大型项目中使用的一样。因此，我们希望Emacs知道如何在与注释相关的项目上下文中评估源代码块。

* direnv as glue
direnv是胶水
:PROPERTIES:
属性:
:CUSTOM_ID: org235c01d
:CUSTOM_ID org235c01d
:END:
结束:

[[https://github.com/direnv/direnv][direnv]] is a shell tool that swaps out a shell environment (in particular, the =PATH= variable) based on the current directory. When your working directory is that of your project, all your project specific tools are in scope (i.e. on =PATH=). When you switch to the directory of another project, all of that project's tools are in scope. Some =nix= users recognized an opportunity, and worked out fairly magical [[https://github.com/direnv/direnv/wiki/Nix][integration between nix and direnv]]. This lets you specify your project with =nix='s flair for pedantry, then drop into it entirely implicitly based on a working directory. There is yet another group of prodigious developers who like to tie into every other system who have a role to play in our story: emacs users. There is [[https://github.com/wbolster/emacs-direnv][emacs integration with direnv]] that uses the directory of any file you are looking at to trigger =direnv='s =PATH= manipulation behind the scenes. Let's recap: we specify our project with =nix=, we edit files with =emacs=, and =direnv= tells emacs what nix knows.
[[https://github.com/direnv/direnv][direnv]]是一个基于当前目录交换shell环境(特别是=PATH=变量)的shell工具。当您的工作目录是项目的工作目录时，所有项目特定的工具都在范围内(即on =PATH=)。切换到另一个项目的目录时，该项目的所有工具都在范围内。一些=nix=用户发现了一个机会，并做出了相当神奇的[[https://github.com/direnv/direnv/wiki/Nix][nix和direnv的集成]]。这允许您使用=nix=的学究风格来指定您的项目，然后根据工作目录完全隐式地放入其中。还有另外一群开发人员，他们喜欢与在我们的故事中扮演角色的其他系统联系在一起:emacs用户。有一个[[https://github.com/wbolster/emacs-direnv][emacs与direnv集成]]使用您正在查看的任何文件的目录来触发=direnv='s =PATH=幕后操作。让我们回顾一下:我们用=nix=指定项目，用=emacs=编辑文件，然后=direnv=告诉emacs nix知道什么。

* C++
* C + +
:PROPERTIES:
属性:
:CUSTOM_ID: org57d7047
:CUSTOM_ID org57d7047
:END:
结束:

Something missing from most C++ development setups is a REPL suitable for experimentation. Something missing from most development setups with a REPL is a good way of saving REPL sessions for future reference. We'll solve both of those here.
大多数c++开发设置中缺少适合实验的REPL。使用REPL的大多数开发设置中缺少的东西是保存REPL会话以供将来参考的好方法。我们把它们都解出来。

Let's figure out how to load an image and show it in a window using =OpenCV=. This is just one component of our project, but it's something we want to write down. Here is an example =shell.nix= if you want to follow along at home. /(Note: it involves a slow build of a customized OpenCV to make the point that your project's needs are usually special.)/
让我们来看看如何使用=OpenCV=加载图像并在窗口中显示它。这只是我们项目的一个组成部分，但我们想把它写下来。下面是一个示例=shell。如果你想在家里跟着做，就不要做。/(注意:它涉及到一个定制的OpenCV的缓慢构建，以表明您的项目的需求通常是特殊的。

#+BEGIN_EXAMPLE
with (import <nixpkgs> {});
let opencv3gtk = opencv3.override { enableGtk3 = true; }; in
mkShell {
buildInputs = [ opencv3gtk ];
}
#+END_EXAMPLE

We then create an =.envrc= file in our shell so that =direnv= will kick into action.
然后创建一个=。这样=direnv=就会开始工作。

#+BEGIN_EXAMPLE
echo 'use nix' > .envrc
direnv allow
#+END_EXAMPLE

And now we can write a note about using OpenCV. I put mine in a =notes.org= file in each project directory.
现在我们可以写一个关于使用OpenCV的说明。我将我的项目放在每个项目目录中的一个=notes.org=文件中。

#+BEGIN_EXAMPLE
I always forget how to display images with OpenCV (useful for
debugging intermediate image processing steps). Remember to wait for
keyboard input so the window doesn't close immediately!

#+BEGIN_SRC C++ :libs -lopencv_core -lopencv_highgui :results silent
#include <opencv2/opencv.hpp>

int main(void) {
const auto img = cv::imread("hello.jpg");
cv::imshow("Window Title", img);
cv::waitKey();
return 0;
}
#+END_SRC
#+END_EXAMPLE

With our cursor in that source block, we can hit =C-c C-c= to execute it, and a window with our image pops up!
将光标放在源块中，我们可以点击=C-c -c=来执行它，然后弹出一个带有我们的图像的窗口!

* Haskell
* Haskell
:PROPERTIES:
属性:
:CUSTOM_ID: org93133ce
:CUSTOM_ID org93133ce
:END:
结束:

Sometimes we want to do something a little tricky in Haskell that will be embedded within a larger piece of code. Extracting the tricky bit so that we can poke it to see how it reacts is hugely useful. Something I had to do recently involved the =lens= and =aeson= libraries for working with JSON data.
有时我们想在Haskell中做一些棘手的事情，这些事情将嵌入到更大的代码段中。提取棘手的部分，这样我们就可以戳它，看看它是如何反应的，这是非常有用的。最近我不得不做的一件事是使用=lens=和=aeson=库来处理JSON数据。

The main Haskell compiler, GHC, does provide a REPL, but it has a few drawbacks:
主要的Haskell编译器GHC确实提供了一个REPL，但是它有一些缺点:

- It uses slightly different syntax (e.g. multi-line input, pragmas)
-使用稍微不同的语法(如多行输入、语法)
- It does not immediately support use as a playground
-它不立即支持用作游乐场

Here I mean /playground/ as a programming environment that makes it easy to see the effects of small changes. A screenshot of a REPL session can be a useful artifact, but you can not re-run it (perhaps with upgraded software), and you can not easily tweak it to see how it responds.
这里我指的是/playground/作为一种编程环境，它可以很容易地看到小变化的影响。REPL会话的屏幕快照可能是一个有用的工件，但是您不能重新运行它(可能使用升级的软件)，而且您不能轻松地调整它以查看它的响应。

Here is our =shell.nix=,
这是我们的=shell。nix=，

#+BEGIN_EXAMPLE
with (import <nixpkgs> {});
mkShell {
buildInputs = [ (ghc.withPackages (p: [
p.lens p.aeson p.lens-aeson p.text p.vector
]))];
}
#+END_EXAMPLE

Again we create an =.envrc= file to enable =direnv=.
再次创建=。envrc=文件启用=direnv=。

#+BEGIN_EXAMPLE
echo 'use nix' > .envrc
direnv allow
#+END_EXAMPLE

For our notes file, we jump through a small hoop because =org-babel='s support of Haskell is not very robust. For this example, we do not need to support any of =babel='s interesting features like setting parameters for a source block, or persistent sessions. With this in mind, we define our own =runhaskell= language support for =org-babel= in an =elisp= source block. Evaluate that block (with =C-c C-c=) to teach emacs how to use =runhaskell=, and then the subsequent =runhaskell= block can be evaluated.
对于我们的notes文件，我们跳过了一个小范围，因为=org-babel=对Haskell的支持不是很强大。对于本例，我们不需要支持任何=babel=的有趣特性，比如为源块设置参数或持久会话。考虑到这一点，我们在=elisp=源块中定义了=org-babel=的=runhaskell=语言支持。计算那个块(用=C-c -c=)来教emacs如何使用=runhaskell=，然后可以计算后面的=runhaskell=块。

#+BEGIN_EXAMPLE
* Preamble
Teach emacs how to use =runhaskell=

#+BEGIN_SRC elisp :results silent
(defun org-babel-execute:runhaskell (body params)
(org-babel-eval "runhaskell"
(org-babel-expand-body:generic body params)))
(add-to-list 'org-src-lang-modes '("runhaskell" . haskell))
#+END_SRC

* Deep JSON Traversal

I have a JSON document that is a nested list of single-field objects
instead of a top-level object with multiple fields, and I want to
flatten the list. I am using
[[https://hackage.haskell.org/package/lens-4.17/docs/Control-Lens-Plated.html#v:deep][deep]]=lens= package to do this. Its type doesn't make it obvious
what it does, so here is a example of how we are using it.

#+BEGIN_SRC runhaskell :results output
{-# LANGUAGE OverloadedStrings #-}
import Control.Lens (view, deep)
import Data.Aeson
import Data.Aeson.Lens (_Object)
import Data.Text (Text)
import Data.Vector (fromList)

array :: [Value] -> Value
array = Array . fromList

main :: IO ()
main = print (view (deep _Object) x)
where x = array [ object [ "name" .= ("Bob" :: Text) ]
, array [ object ["age" .= (64 :: Int) ]
, array [] ] ]
#+END_SRC

#+RESULTS:
: fromList [("age",Number 64.0),("name",String "Bob")]
#+END_EXAMPLE

* Not Perfect
*不完美
:PROPERTIES:
属性:
:CUSTOM_ID: org0b4e715
:CUSTOM_ID org0b4e715
:END:
结束:

When doing any substantial programming, I use [[https://github.com/MaskRay/ccls/][ccls]] or [[https://github.com/cquery-project/cquery][cquery]] for C++, and [[https://github.com/commercialhaskell/intero][intero]] for Haskell. I have not worked out how to directly wire such tools in to writing notes as shown above. The main challenge is that external tooling really wants to work with files on disk, while we're trying to move beyond that here.
在做任何实质性的编程时，我使用[[https://github.com/MaskRay/ccls/][ccls]]或[[https://github.com/cquery-project/cquery][cquery]]用于c++，而[[https://github.com/commercialhaskell/intero][intero]]用于Haskell。我还没有想出如何直接把这些工具连接到写笔记如上所示。主要的挑战是，外部工具确实需要处理磁盘上的文件，而我们正在尝试超越这一点。

If you have your tooling setup to work for any files in your project directory, I recommend investigating =org-babel-tangle=. Making this work requires only that you add =:tangle my-example.hs :comments link= to your =runhaskell= source block header. Then you can use =org-babel-tangle= (=C-c C-v t=) to write your source block to the named file. That file will let you use a tool like =intero= to help you write more of your example program, and, when you're ready, you can run =org-babel-detangle= in the buffer where you edited the =my-example.hs= file to sync your changes back to the org file.
如果您已经为项目目录中的任何文件设置了工具，我建议您调查=org-babel-tangle=。使这个工作只需要您添加=:tangle my-example。hs:注释链接=到您的=runhaskell=源块头。然后可以使用=org-babel-tangle= (=C-c C-v t=)将源块写入指定文件。该文件将允许您使用=intero=之类的工具来帮助您编写更多示例程序，并且，当您准备好时，可以在编辑=my-example的缓冲区中运行=org-babel-detangle=。将您的更改同步回组织文件。

Alternately, you can manually include a separate source file into your org notes like this:
或者，你可以手动将一个独立的源文件包含到你的组织中，就像这样:

#+BEGIN_EXAMPLE
I wrote this example code with fancy tooling, but I'd like to talk
about it here and see its output.

#+INCLUDE: "test.hs" src runhaskell

#+BEGIN_SRC runhaskell :exports results :prologue (with-temp-buffer (insert-file-contents "test.hs") (buffer-string))
#+END_SRC

#+RESULTS:
: fromList [("age",Number 64.0),("name",String "Bob")]
#+END_EXAMPLE

When you export your org notes, the file's source will show up thanks to the =#+INCLUDE:= directive, and the output will show up thanks to the source block with the =:prologue= header. If you're doing this often, you will probably want to define a helper to make that =:prologue= a bit more terse, or define a snippet to generate the whole blob of boilerplate. That said, I find this option less appealing since you no longer see your source code and its output in the same file.
当您导出org注释时，文件的源代码将显示在=#+INCLUDE:=指令中，输出将显示在具有=:prologue= header的源代码块中。如果您经常这样做，您可能希望定义一个帮助器，使=:prologue=更简洁一些，或者定义一个代码片段来生成整个样板文件。也就是说，我发现这个选项不太吸引人，因为您不再在同一个文件中看到源代码及其输出。
