#+TITLE: 一个 CEO 的 Emacs 指南
#+URL: https://blog.fugue.co/2015-11-11-guide-to-emacs.html
#+AUTHOR: Samray
#+CATEGORY: emacs-common
#+DATE: <2017-04-04 Tue>
#+OPTIONS: ^:{}

约数年前，噢，不，是数十年前了，我就生活在 Emacs. 编写代码和文档，管理邮件和日程，
以及使用 shell 自动化一切的操作，这些活动都是在我的编辑器(或者说是操作系统)上完成
的;这样的生活我过得真的很开心。数十春秋寒暑过去了，我也用上了其他更加新，更加潮
的玩意了。结果呢，我却已经忘记了如何在脱离鼠标的情况下高效地浏览，跳转文件了。大
概是三个月前吧，我注意到我有大量的时间是浪费在不同的应用程序和电脑之间的来回切换，
我决定再次投入 Emacs 的怀抱，这是一个非常正确的决定，为什么这么说？原因我会在接下
来的段落里面说明，此外我还会介绍我的 Emacs 配置以及 Dropbox 的技巧，以构建一个可迁
移的环境。

对于那些未曾使用过 Emacs 的人而言，Emacs 很可能是你现在所厌恶，但最终喜爱的东西。乍
一看，你会觉得 Emacs 是一台房子那么大的却拥有只烤面包机全部功能的 Rube Goldberg
machine (译者注：这是卡通中的一种完成简单任务的非常复杂的机器).很难说这样的话是
对 Emacs 的一种赞美，不过请留意 *乍一看* 这个非常重要的词。因为当你真的深入了解
Emacs 之后，你就会发现 Emacs 即使是烤面包机，也是一台可以当引擎用的 "核能烤面包机
",可以处理任何你想处理的文本。当你意识到你有多少时间是花在处理文本上，你就会觉得
你说"Emacs 是像引擎一样强大"的言论是相当大胆激进；虽说这有点惊世骇俗，但这就是事
实

可能对于我来说，更重要的是，使用的是一个让我感觉到我是拥有它的程序，而不是那些让
我觉得我只是扮演一个匿名的用户，并且会被它位于 Soma 或者 Redmond (译者注 :微软公
司所在地之一) 的市场营销部门窥探钱包，想方设法让我付钱的程序。现代的生产或者创作
工具 (例如，Page 或 IDE) 都像碳纤维自行车那样;它们可以很轻易地进行拆卸和组装。
Emacs 就好像满箱子的经典 Campagnolo (译者注：高端自行车部件)部件和非常好的钢制框
架，只是缺了一个曲柄臂和制动杠，你必须自己去网上搜寻你缺少的部件。Emacs 的第一个
特点就是快和完整，第二个特点就是带给你的余生无尽的快乐 (或者是烦恼，就取决于你是
什么样的人了).我自己就是那种会在找寻老古董或者折腾编辑器中得到很多乐趣的人了。这
个就因人而异了

[[https://camo.githubusercontent.com/501cde22bde7a7411ad1cb7f1ce837833b7107b7/68747470733a2f2f626c6f672e66756775652e636f2f6173736574732f696d616765732f62696379636c652e6a7067]]

我现在仍在骑的 1933 钢制自行车。有兴趣的可以看一下不同材料的自行车车架的比较
[[https://www.youtube.com/watch?v=khJQgRLKMU0]]

可能有时 Emacs 给人的感觉是不合时宜的老古董，这种看法并不正确。Emacs 是非常强大
并且可以与时俱进的，但是 Emacs 需要你耐心地理解它的哲学。而 Emacs 的哲学又是那样
的与众不同，甚至可以说是怪异；在了解 Emacs 以后，你又会发现 Emacs 是那般的引人入
胜。对我而言，Emacs 更像未来的产物，而不是过时的古董; 就好像钢制车架会在未来大行
其道，而碳纤维车架最终会无人问津那样; 也正如那些最新潮的应用都会被遗忘在历史的洪
流中，而 Emacs 会恒久远，永流传。

如果你热忱于使用 Lisp 打造适合自己的并且可以在任何电脑移植的工作环境的话，你一定
会爱上 Emacs. 但是如果你喜欢那些新朝，开箱即用，无需额外投资时间精力学习的工作环
境的话，Emacs 可能就不适合你了。我已经没有编写代码了 (除了 Ludwig 和 Emacs
Lisp), 但是我发现大部份在 Fugue (译者注：作者所在的公司) 的工程师都可以高效地使
用 Emacs. 在 Fugue, 大概 30% 的工程师使用 Emacs , 40% 的工程师使用 IDE, 30% 的工
程师使用 Vim. 而本文是写给 CEO 以及其他的 PHB 的(Pointy-Haired Boss 译者注：漫画
中的蠢蠢的老板)(当然，也写给所有对 Emacs 感兴趣的人). 所以我接下来会解释我为什么
那喜爱 Emacs 以及我是怎么使用 Emacs 的。我希望可以为你提供足够多的细节， 以便你
不用 google 就可以玩转 Emacs. 如果你也喜欢我的 Emacs 环境，你可以把我的 [[https://blog.fugue.co/2015-11-11-guide-to-emacs.html?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io#download][Emacs
configuration]] 下载下来
* Lasting Advantages
  使用 Emacs 的长期好处就是你的生活会变得更加简单，而对 Emacs 的投入产出比会让你觉
  得学习 Emacs 时非常值得的。考虑一下下面这些内容：
** No more Context Switching
   如果你像我那样，需要经常处理大量的文档 -- 从博文到需要员工 review 的会议上的
   资料，那么你花费时间去单独学习 Org-mode 就非常由必要了。在现代的计算世界，上
   述的这些文档工作意味着你需要若干不同的程序，而这些程序有各种令人分心的用户接
   口，以及使用不同的方式来进行保存，排序，搜索。结果就是你需要在各种不同的内容
   之间切换，并要记住它们之间的细节。我讨厌这样的切换，我讨厌因为这种不友好的设
   计而导致的不必要的负担，我讨厌我需要记住这些本应该由电脑记住的内容。就提供一
   个单一的环境而言，Emacs 对于 PHB ,会比对于程序员而言更加强大，因为程序员一天
   大部份的时间都会专注在第一的引用。而且，在不同内容切换所花费的代价会要比我们
   所了解的高。操作系统和那些程序通过修饰用户接口以粉饰这个真相。如果你是一个技
   术人员，使用一个单独的快捷键就可以调用一个强大的语言解释器是非常有用的。

