#+URL: http://jjasghar.github.io/blog/2017/01/04/changing-fonts-in-emacs/

Something I can never remember is how fonts are set in emacs. Here are some notes on how I figured it out.

First thing first, figure out what font you’re using. Open up your *scratch* buffer and type:

#+BEGIN_SRC emacs-lisp
  (face-attribute 'default :font)
#+END_SRC

In your minibuffer you should see the font name. I suggest moving over to the *Messages* buffer yanking it and putting it in your
*scratch* buffer with a ; in front of it. (Notes are useful yeah?)

Lets set a default font now, take the following and eval it in your *scratch* buffer.

#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'default nil :font "-outline-Monaco-normal-normal-normal-mono-16-*-*-*-c-*-iso8859-1" )
#+END_SRC

Yay! You should have changed your font, to take from the [[https://www.emacswiki.org/emacs/SetFonts][wiki]] this “…change the default font for the current frame, as well as future
frames…”

Now if you want to change the default font, but not the current frame, run the following:

#+BEGIN_SRC emacs-lisp
  (set-face-attribute 'default t :font "-outline-Monaco-normal-normal-normal-mono-16-*-*-*-c-*-iso8859-1" )
#+END_SRC

After posting this to [[https://www.reddit.com/r/emacs/comments/5m0nig/notes_on_how_to_change_fonts_in_emacs_without/][reddit]], [[https://www.reddit.com/user/eli-zaretskii][eli-zaretskii]] suggested using:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(font . "your-font-name-here"))
#+END_SRC

Which works, but doesn’t seem to update the current buffer. If you’re testing out different fonts, personally, I’d like to see the effect
without reloading.

If you haven’t realized, the 16 is the font size in the line, personally 20 feels better, but you get the point. (eh? get it? eh? point?)

If you want to find other fonts, to play around with check out [[https://www.emacswiki.org/emacs/GoodFonts][here]].

When you figure out what you want, you should add the default nil line to your init.el so every time you start emacs your font is
configured.
