#+TITLE: Difference-between-Org-mode-and-Hyperbole
#+AUTHOR: lujun9972
#+URL: https://lists.gnu.org/archive/html/emacs-devel/2016-06/msg00246.html                                 
#+CATEGORY: raw
#+DATE: [2016-08-05 五 12:54]
#+OPTIONS: ^:{}

On Wed, Jun 15, 2016 at 3:56 PM, Tom <[[mailto:address@hidden][address@hidden]]> wrote:

    It would be useful if you could compare it to something which
    people know. For example, Org mode is part of Emacs and from the
    description it seems to me Hyperbole has some overlapping functionality
    with Org (e.g. org also has outlining ability, it can also be a
    personal information manager, can link to other files, etc.)
   
    What are the differences?

Although on the surface this comes up a lot, once you use both of these, you'll quickly see how different they
are.  Because they are so different, it is likely that there will be some integration in the future.

Org-mode is a major-mode that works on structured files built atop Emacs outlining mode.
Hyperbole is a system that spans across much of Emacs' functionality, providing quick access keys and
hyperbuttons wherever needed.

Org-mode's outliner is like Emacs outliner.
Hyperbole's Koutliner is unique; every node/paragraph has a unique id and settable attributes plus a relative
id that is auto-updated as you move trees around the outline, so you know that node 2b4 is a child of 2b and
is the next sibling of the 2b3 node.

Org-mode has explicit hyperlinks that you create.
Hyperbole has these too, allowing you to create them in any type of text file, with simple drags between
windows.  But Hyperbole also recognizes hyperlinks embedded in many different types of files and buffers and
can easily support new types.  You simply press one button and Hyperbole figures out what to do in dozens of
contexts.

Org-mode manages todos, time entries and some basic project management.
Hyperbole does none of this except you can integrate with whatever todo management you like.

Org-mode doesn't have any contact management as far as I know (which is not much since I have not yet used
it).
Hyperbole has a fast, effective hierarchical contact manager.

Org-mode does nothing with your buffers, windows and frames since it is just a major mode.
Hyperbole has a fast, thoughtfully designed window and frame manager that lets you quickly arrange your Emacs
artifacts as you like.  Eventually, these window and frame configurations will be saveable and will be able to
be the target of links, so you can have quick access buttons that arrange things for different work tasks
(similar to Workspaces but integrated with all of Hyperbole's other features).

Org-mode does nothing for management of libraries of information.
Hyperbole helps organize, link, search and retrieve libraries of text files.

Hyperbole also has features that speed code browsing and structured code editing and support for using the
mouse keys as Control and Meta modifiers so you can point and operate on screen entities quickly.

Does that help?

If you want to know more, sit down after work and read the manual.  It will tell you a lot.

Bob
