#+TITLE: Displaying animated diagrams in org-reveal slide decks with SVG – WebLog Pro Olivier Berger
#+URL: https://www-public.imtbs-tsp.eu/~berger_o/weblog/2019/11/26/displaying-animated-diagrams-in-org-reveal-slide-decks-with-svg/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2020年 01月 15日 星期三 19:22:57 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
[[https://github.com/yjwen/org-reveal/][org-reveal]] can be used to author slide decks with org-mode. The slides are displayed as an HTML document animated with [[https://revealjs.com/][reveal.js]].

reveal.js allows to progressively display fragments which reveal parts of a page, for instance a bullet list.

It is also possible to display animated diagrams, as reveal.js fragments, provided that such diagrams are made as embedded SVG images included in the HTML.

Adding =class="fragment"= (and variations, including the associated =data-fragment-index= attributes) to the SVG elements helps animate parts of the diagram with the same JS actions as for regular bullet fragments.

The trick is to embed the SVG diagram inside the HTML source using the following code in the org-mode source:

#+BEGIN_EXAMPLE
  #+BEGIN_EXPORT html
  <svg ...> 
   ...
  </svg> 
  #+END_EXPORT
#+END_EXAMPLE

I've found inspiration for that trick seeing the way SVG content was animated in [[https://inkscape.org/~doctormo/%E2%98%85group-photo-web-css-popover][the following demo]].

So far, I've edited my diagrams with inkscape, and finally copied the whole <svg> tag from the saved inkscape file, into the =#+BEGIN_EXPORT= embedded HTML of the org file.

You can see a demo of such an animation in the [[https://olberger.gitlab.io/org-teaching/slides.html]] document (slide 26: “Fragmented SVG display”).

Hope this helps.
