#+TITLE: Emacs #3: More on org-mode
#+URL: http://changelog.complete.org/archives/9877-emacs-3-more-on-org-mode
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 03月 06日 星期二 10:15:11 CST]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
This is third in [[https://changelog.complete.org/archives/tag/emacs2018][a series on Emacs and org-mode]].
这是[[https://changelog.complete.org/archives/tag/emacs2018][关于Emacs和组织模式的系列]]中的第三个。

* Todo tracking and keywords
*待办事项跟踪和关键词

When using org-mode to [[https://orgmode.org/guide/TODO-Items.html#TODO-Items][track your TODOs]], it can have multiple states. You can press =C-c C-t= for a quick shift between states. I have set this:
当使用org-mode来[[https://orgmode.org/guide/TODO-Items.html#TODO-Items][跟踪你的TODOs]]时，它可以有多个状态。您可以按=C-c C-t=快速切换状态。我设置了这个:

#+BEGIN_EXAMPLE
(setq org-todo-keywords '(
(sequence "TODO(t!)" "NEXT(n!)" "STARTED(a!)" "WAIT(w@/!)" "OTHERS(o!)" "|" "DONE(d)" "CANCELLED(c)")
))
#+END_EXAMPLE

Here, I set up 5 states that are for a task that is not yet done: TODO, NEXT, STARTED, WAIT, and OTHERS. Each has a single-character shortcut (t, n, a, etc). The states after the pipe symbol are ones that are considered “done”. I have two: DONE (for things that I have done) and CANCELED (for things that I haven't done, but for whatever reason, won't).
这里，我为尚未完成的任务设置了5个状态:TODO、NEXT、STARTED、WAIT和其他。每个都有一个单字符的快捷方式(t、n、a等)。管道符号之后的状态被认为是“完成”的状态。我有两个选择:做(我已经做过的事)和取消(我还没有做过的事，但无论出于什么原因，我都不会做)。

The exclamation mark means to log the time when an item was changed to a state. I don't add this to the done states because those are already logged anyhow. The @ sign means to prompt for a reason; so when switching to WAIT, org-mode will ask me why and add this to the note.
感叹号表示记录某项更改为状态的时间。我没有将这个添加到已完成状态中，因为这些状态已经被记录了。@符号表示提示某个原因;因此，当切换到等待，组织模式会问我为什么，并添加到笔记。

Here's an example of an entry that has had some state changes:
下面是一个条目的例子，它有一些状态变化:

#+BEGIN_EXAMPLE
** DONE This is a test
CLOSED: [2018-03-02 Fri 03:05]
- State "DONE" from "WAIT" [2018-03-02 Fri 03:05]
- State "WAIT" from "TODO" [2018-03-02 Fri 03:05] \
waiting for pigs to fly
- State "TODO" from "NEXT" [2018-03-02 Fri 03:05]
- State "NEXT" from "TODO" [2018-03-02 Fri 03:05]
#+END_EXAMPLE

Here, the most recent items are on top.
这里，最新的项目在上面。

*Agenda mode, schedules, and deadlines*
*议程模式、时间表和截止日期*

When you're in a todo item, C-c C-s or C-c C-d can set a schedule or a deadline for it, respectively. These show up in agenda mode. The difference is in intent and presentation. A schedule is something that you expect to work on at around a time, while a deadline is something that is due at a specific time. By default, the agenda view will start warning you about deadline items in advance.
当你在做待办事项时，C-c C-s或C-c C-d可以分别为它设定一个时间表或最后期限。这些显示在日程模式中。区别在于意图和表达。日程表是你希望在某个时间完成的事情，而deadline是在某个特定时间截止的事情。默认情况下，日程视图将开始提前警告您截止日期项。

And while we're at it, the [[https://orgmode.org/guide/Agenda-Views.html#Agenda-Views][agenda view]] will show you the items that you have coming up, offers a nice way to search for items based on plain text or tags, and handles bulk manipulation of items even across multiple files. I covered setting the files for agenda mode in [[https://changelog.complete.org/archives/9865-emacs-2-introducing-org-mode][part 2]] of this series.
虽然我们,[[https://orgmode.org/guide/Agenda-Views.html Agenda-Views][日程视图]]将向您展示的物品,提供了一个很好的方式来搜索项基于纯文本或标签,甚至处理批量操作的项目跨多个文件。我介绍了在本系列的[[https://changelog.complete.org/archives/9865-emacs-2- introduction -org-mode][第2部分]]中设置议程模式的文件。

* Tags
*标记

Of course org-mode has [[https://orgmode.org/guide/Tags.html#Tags][tags]]. You can quickly set them with C-c C-q.
当然，org-mode有[[https://orgmode.org/guide/Tags.html#Tags][Tags]]。你可以用C-c - C-q快速设置它们。

You can set shortcuts for tags you might like to use often. Perhaps something like this:
您可以为您可能经常使用的标记设置快捷方式。也许是这样的:

#+BEGIN_EXAMPLE

(setq org-tag-persistent-alist
'(("@phone" . ?p)
("@computer" . ?c)
("@websurfing" . ?w)
("@errands" . ?e)
("@outdoors" . ?o)
("MIT" . ?m)
("BIGROCK" . ?b)
("CONTACTS" . ?C)
("INBOX" . ?i)
))
#+END_EXAMPLE

You can also add tags to this list on a per-file basis, and also set tags for something on a per-file basis. I use that for my inbox.org and email.org files to set an INBOX tag. I can then review all items tagged INBOX from the agenda view each day, and the simple act of refiling them into other files will cause them to lost the INBOX tag.
您还可以在每个文件的基础上向这个列表添加标记，也可以在每个文件的基础上为某些内容设置标记。我将它用于我的inbox.org和email.org文件来设置收件箱标签。然后我可以每天从日程视图中查看所有标记为INBOX的条目，而将它们重新归档到其他文件的简单操作将导致它们丢失INBOX标记。

* Refiling
*接力传送

“Refiling” is moving things around, either within a file or elsewhere. It has completion using your headlines. =C-c C-w= does this. I like these settings:
“重新归档”是指在一个文件或其他地方移动文件。它已经完成使用您的标题。=C-c C-w=做这个。我喜欢这些设置:

#+BEGIN_EXAMPLE

(setq org-outline-path-complete-in-steps nil) ; Refile in a single go
(setq org-refile-use-outline-path 'file)
#+END_EXAMPLE

* Archiving
*存档

After awhile, you'll get your files all cluttered with things that are done. org-mode has an [[https://orgmode.org/guide/Archiving.html#Archiving][archive]] feature to move things out of your main .org files and into some other files for future reference. If you have your org files in git or something, you may wish to delete these other files since you'd have things in history anyhow, but I find them handy for grepping and searching.
一段时间之后，你会发现你的文件里堆满了要做的事情。org-mode有一个[[https://orgmode.org/guide/Archiving.html#Archiving][archive]]特性，可以将文件从主要的org文件移到其他文件中，以供将来参考。如果你有你的组织文件在git或其他东西，你可能希望删除这些其他文件，因为你无论如何在历史上有东西，但我发现他们方便的grepping和搜索。

I periodically want to go through and archive everything in my files. Based on a [[https://stackoverflow.com/questions/6997387/how-to-archive-all-the-done-tasks-using-a-single-command][stackoverflow discussion]], I have this code:
我想定期浏览并把所有东西都归档。基于一个[[https://stackoverflow.com/questions/6997387/how to archi- all-the-do -tasks-using-a-single-command][stackoverflow discussion]]，我有这样的代码:

#+BEGIN_EXAMPLE

(defun org-archive-done-tasks ()
(interactive)
(org-map-entries
(lambda ()
(org-archive-subtree)
(setq org-map-continue-from (outline-previous-heading)))
"/DONE" 'file)
(org-map-entries
(lambda ()
(org-archive-subtree)
(setq org-map-continue-from (outline-previous-heading)))
"/CANCELLED" 'file)
)
#+END_EXAMPLE

This is based on [[https://stackoverflow.com/a/27043756][a particular answer]] --- see the comments there for some additional hints. Now you can run =M-x org-archive-done-tasks= and everything in the current file marked DONE or CANCELED will be pulled out into a different file.
这是基于[[https://stackoverflow.com/a/27043756][一个特定的答案]]——查看那里的评论以获得一些额外的提示。现在您可以运行=M-x org-archive-done-tasks=，并且当前文件中标记为DONE或cancel的所有内容将被拉出到另一个文件中。

* Up next
*下一个

I'll wrap up org-mode with a discussion of automatically receiving emails into org, and syncing org between machines.
我将结束组织模式与讨论自动接收电子邮件到组织，并同步组织之间的机器。
