#+TITLE: Emacs - An IDE in the Console
#+URL: https://www.linkedin.com/pulse/emacs-ide-console-palmer-cluff/?published=t
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 10月 25日 星期四 12:00:29 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
A lot of developers use IDE's (Eclipse, NetBeans, Visual Studio) and GUI-based text editors (Sublime Text, NotePad++, Atom) for their day-to-day coding tasks. At times, one may need to edit a remote file and you typically have one of two options:
许多开发人员使用IDE (Eclipse、NetBeans、Visual Studio)和基于gui的文本编辑器(Sublime text、notepad++、Atom)来完成日常的编码任务。有时，你可能需要编辑一个远程文件，你通常有两种选择:

1. Edit the file remotely in the terminal via Vim, Emacs, or Nano
1. 通过Vim、Emacs或Nano在终端远程编辑文件
2. Download the file locally, edit using your favorite IDE or GUI editor, then upload it again to the server
2. 在本地下载文件，使用您喜欢的IDE或GUI编辑器进行编辑，然后再次将其上载到服务器

Both ways work, but working remotely with console-based editors can be a bit of a pain, and sometimes you may not be in a situation to use the software of your choice to edit the file(s) locally (like when you are using a colleagues computer and they won't let you install anything).
两方面的工作,但与控制台的编辑可以远程工作有点疼痛,有时你可能不是在一个情况下使用您所选择的软件编辑本地文件(s)(比如当你使用同事的电脑,他们不会让你安装任何东西)。

Well, there just so happens to be some Emacs packages you can enable to have your remote (or local) Emacs text editor behave more like your favorite IDE or GUI editor.
好吧，正好有一些Emacs包，您可以使您的远程(或本地)Emacs文本编辑器的行为更像您喜欢的IDE或GUI编辑器。

As a note, this is *not* an anti-Vim or anti-GUI rant, these are just some pointers on how to extend your Emacs configuration to behave more like a minimal non-bloated IDE, and less like a hard-to-use-too-many-extra-features text editor.
需要注意的是，这并不是“反vim”或“反gui”的夸夸谈，这些只是一些关于如何扩展Emacs配置，使其表现得更像一个最小的无膨胀的IDE，而不像一个难以使用的、有太多额外特性的文本编辑器的一些指示。


** Code Formatting
* *代码格式化
:PROPERTIES:
属性:
:CUSTOM_ID: code-formatting
:CUSTOM_ID:代码
:END:
结束:

Emacs has various "modes" for some of the most common programming languages (C, C++, Java, HTML, JavaScript, Python, etc) to help format code. If you want to indent a code block, Emacs already has you covered and will indent the next line automatically. You may find that some language modes are not already built in (such as PHP, Lua, and some of the newer ones), but they can be easily added at a whim's notice.
Emacs为一些最常见的编程语言(C、c++、Java、HTML、JavaScript、Python等)提供了各种“模式”来帮助格式化代码。如果您想缩进一个代码块，Emacs已经为您准备好了，并将自动缩进下一行。您可能会发现，有些语言模式还没有内置(如PHP、Lua和一些较新的语言模式)，但是您可以随时添加它们。

[[https://media.licdn.com/dms/image/C4E12AQFw37wEDHQySw/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=jRWSXAAmSc7kKr1sq2Xrc26vIofk52gsQJGqLsxCWQA]]
[[https://media.licdn.com/dms/image/C4E12AQFw37wEDHQySw/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=jRWSXAAmSc7kKr1sq2Xrc26vIofk52gsQJGqLsxCWQA]]


** Auto-completion
* *自动完成
:PROPERTIES:
属性:
:CUSTOM_ID: auto-completion
:CUSTOM_ID:自动完成
:END:
结束:

Auto-completion is a feature not typically found in text-based editors. This feature is not built in, but if you want to add this you can use the [[https://github.com/auto-complete/auto-complete][Auto-Complete]] Emacs library that gives you a nice IntelliSense-like menu. Emacs can also auto-close parenthesis, brackets, quotes, and other characters that are commonly paired together.
自动完成是基于文本的编辑器中通常找不到的特性。这个特性不是内建的，但是如果你想添加它，你可以使用[[https://github.com/auto-complete/auto-complete][Auto-Complete]] Emacs库，它会给你一个类似于intellisense的菜单。Emacs还可以自动关闭括号、方括号、引号和其他通常组合在一起的字符。

[[https://media.licdn.com/dms/image/C4E12AQFlzeAghZSGoA/article-inline_image-shrink_1000_1488/0?e=1545868800&v=beta&t=DX7C5E_cEghHmccwIopzFAkaxcZLgGWVScoQqTrCyIg]]
[[https://media.licdn.com/dms/image/C4E12AQFlzeAghZSGoA/article-inline_image-shrink_1000_1488/0?e=1545868800&v=beta&t=DX7C5E_cEghHmccwIopzFAkaxcZLgGWVScoQqTrCyIg]]

** Spell-checking
* *拼写检查
:PROPERTIES:
属性:
:CUSTOM_ID: spell-checking
:CUSTOM_ID:拼写检查
:END:
结束:

Emacs has spell-checking built in. By default it uses an English dictionary, but this can be changed along with adding your own words to a personal dictionary file to help avoid false positives. You can also set it where you only want Emacs to spell-check comments and strings and to ignore all other programming-specific sections of code.
Emacs内置了拼写检查功能。默认情况下，它使用的是英语词典，但也可以通过将自己的单词添加到个人词典文件中来避免误报。您还可以将它设置在只希望Emacs检查拼写注释和字符串并忽略所有其他与编程相关的代码部分的地方。

[[https://media.licdn.com/dms/image/C4E12AQE5J4WX6I4nLQ/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=8lrw0PC_BejclkLAs_ehbS6ecyPchI52ZcCUrpdt2Hw]]
[[https://media.licdn.com/dms/image/C4E12AQE5J4WX6I4nLQ/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=8lrw0PC_BejclkLAs_ehbS6ecyPchI52ZcCUrpdt2Hw]]

** Personal Extensions
* *个人扩展
:PROPERTIES:
属性:
:CUSTOM_ID: personal-extensions
:CUSTOM_ID personal-extensions
:END:
结束:

Emacs is open-sourced, and the code base is available to everyone. Using Emacs' built-in language (Emacs Lisp; or Elisp as most call it), you can extend Emacs by writing your own functions and packages. Below is a short function that will automatically add a closing HTML tag as soon as the opening tag has been typed only if the user is editing an HTML file:
Emacs是开源的，代码库对每个人都是可用的。使用Emacs的内置语言(Emacs Lisp;您可以通过编写自己的函数和包来扩展Emacs。下面是一个简短的函数，它将自动添加一个关闭的HTML标签，只要打开标签已经键入，只有当用户正在编辑一个HTML文件:

[[https://media.licdn.com/dms/image/C5612AQF2uPYbmnAEPw/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=5YGijg-5LBQeqmOhlGJrlSJapbMynoJ7Z_s9U-2nBYc]]
[[https://media.licdn.com/dms/image/C5612AQF2uPYbmnAEPw/article-inline_image-shrink_1500_2232/0?e=1545868800&v=beta&t=5YGijg-5LBQeqmOhlGJrlSJapbMynoJ7Z_s9U-2nBYc]]

** Other Customizations
* *其他定制
:PROPERTIES:
属性:
:CUSTOM_ID: other-customizations
:CUSTOM_ID:进行其他的定制工作
:END:
结束:

There are loads of other features that can easily be enabled or disabled to make Emacs perform like your personally-made IDE. Some include:
还有许多其他的特性可以很容易地启用或禁用，以使Emacs像您的个人IDE一样执行。一些包括:

- Keybindings
-快捷键
- Macros
-宏
- SSH/SCP remote file editing support
- SSH/SCP远程文件编辑支持
- xterm mouse support
- xterm鼠标支持
- UI modifications
——用户界面的修改
- Abbreviation expansions
——简称扩张
- Automatic file backup
-自动备份档案
- Embedded file explorer
-嵌入式文件资源管理器
- Babel support for having multiple programming languages in the same file
- Babel支持在同一个文件中有多种编程语言
- File encryption
——文件加密
- And more!
和更多!

** Takeaway
* *外卖
:PROPERTIES:
属性:
:CUSTOM_ID: takeaway
:CUSTOM_ID:外卖
:END:
结束:

Emacs is extremely extendable, but may not be for the faint of heart. To make Emacs behave exactly like you want it, prepare to spend a lot of time tinkering with the range of features and open-source packages available for it. Whatever time you spend tweaking Emacs to behave like your own IDE will definitely be worth it!
Emacs是非常可扩展的，但可能不适合胆小的人。要使Emacs的行为完全符合您的期望，您需要准备花费大量时间来修补可用的特性和开放源码包。无论您花费多少时间来调整Emacs，使其表现得像您自己的IDE一样，都绝对是值得的!
