#+TITLE: Emacs with Wanderlust and GMail
#+URL: https://box.matto.nl/emacsgmail.html
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 06月 22日 星期五 15:04:22 CST]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* Emacs with Wanderlust IMAP mailclient
   :PROPERTIES:
   :CUSTOM_ID: emacs-with-wanderlust-imap-mailclient
   :END:

You have multiple workstations from which you want to approach your email. Maybe because you use both your workstation and your laptop. Or because you want to use email from different locations. Whatever the reason, if you have more than one computer from which you want to have access to your mailboxes, [[http://nl.wikipedia.org/wiki/Internet_Message_Access_Protocol][IMAP]] can provide a good way to get things nicely organized. You could also use a [[http://www.intermedia.net][hosted exchange]] service for extra organization.

The [[http://crc.nd.edu/software/xemacs.shtml][IMAP]] protocol let you access your mailboxes, open emails to read without removing the mail from the mailserver. So the next time you log in, your email is still there. (Exept when you deliberately want to delete mail).

Most pop3-mailservers can do IMAP.

To approach an IMAP mailserver from within [[http://en.wikipedia.org/wiki/Emacs][Emacs]], you need to install additional software in Emacs. Wanderlust is an proven solution to add IMAP capabilities to Emacs.

* Wanderlust and GMail HOWTO
   :PROPERTIES:
   :CUSTOM_ID: wanderlust-and-gmail-howto
   :END:

It is very easy to configure Wanderlust to access your [[http://www.gmail.com][GMail]] account.

Here are the steps to do so:

1. Get wanderlust
2. Create ~/.folders
3. Append the wanderlust configuration to ~/.emacs
4. Start emacs, start wanderlust and enjoy the most effecient and effective GMail client in the world

** Get wanderlust
    :PROPERTIES:
    :CUSTOM_ID: get-wanderlust
    :END:

#+BEGIN_EXAMPLE
    apt-get install wl
#+END_EXAMPLE

If you don't have Debian, this is where you can find [[http://www.gohome.org/wl/][Wanderlust]]

** Create ~/.folders
    :PROPERTIES:
    :CUSTOM_ID: create-.folders
    :END:

If you don't have Debian, this is where you can find [[http://www.gohome.org/wl/][Wanderlust]]

This is the minimal content of ~/.folders:\\

#+BEGIN_EXAMPLE
    %inbox "inbox"
    +trash "Trash"
    +draft "Drafts"
#+END_EXAMPLE

** Append the wanderlust configuration to ~/.emacs
    :PROPERTIES:
    :CUSTOM_ID: append-the-wanderlust-configuration-to-.emacs
    :END:

Put this in your ~/.emacs:

#+BEGIN_EXAMPLE
    ;; wanderlust
    (autoload 'wl "wl" "Wanderlust" t)
    (autoload 'wl-other-frame "wl" "Wanderlust on new frame." t)
    (autoload 'wl-draft "wl-draft" "Write draft with Wanderlust." t)

    ;; IMAP
    (setq elmo-imap4-default-server "imap.gmail.com")
    (setq elmo-imap4-default-user "<accountname>@gmail.com") 
    (setq elmo-imap4-default-authenticate-type 'clear) 
    (setq elmo-imap4-default-port '993)
    (setq elmo-imap4-default-stream-type 'ssl)

    (setq elmo-imap4-use-modified-utf7 t) 

    ;; SMTP
    (setq wl-smtp-connection-type 'starttls)
    (setq wl-smtp-posting-port 587)
    (setq wl-smtp-authenticate-type "plain")
    (setq wl-smtp-posting-user "mattofransen")
    (setq wl-smtp-posting-server "smtp.gmail.com")
    (setq wl-local-domain "gmail.com")

    (setq wl-default-folder "%inbox")
    (setq wl-default-spec "%")
    (setq wl-draft-folder "%[Gmail]/Drafts") ; Gmail IMAP
    (setq wl-trash-folder "%[Gmail]/Trash")

    (setq wl-folder-check-async t) 

    (setq elmo-imap4-use-modified-utf7 t)

    (autoload 'wl-user-agent-compose "wl-draft" nil t)
    (if (boundp 'mail-user-agent)
     (setq mail-user-agent 'wl-user-agent))
    (if (fboundp 'define-mail-user-agent)
     (define-mail-user-agent
     'wl-user-agent
     'wl-user-agent-compose
     'wl-draft-send
     'wl-draft-kill
     'mail-send-hook))
#+END_EXAMPLE

** Start emacs, start wanderlust and enjoy the most effecient
and effective GMail client in the world
    :PROPERTIES:
    :CUSTOM_ID: start-emacs-start-wanderlust-and-enjoy-the-most-effecient-and-effective-gmail-client-in-the-world
    :END:

Start emacs and do

#+BEGIN_EXAMPLE
    M-x wl
#+END_EXAMPLE

\\
Now you will be prompted for your gmail password. After this, you can access your gmail inbox.

Now you will be prompted for your gmail password. After this, you can access your gmail inbox.

If you want to open other mailboxes besides inbox you should add them to your ~/.folders (I have not tested this).

You can send email through your gmail account to. Create a new mail in Wanderlust and send it. You will be prompted for your password again and your mail is sent.

* Encrypt your messages
   :PROPERTIES:
   :CUSTOM_ID: encrypt-your-messages
   :END:

It is a good habit to encrypt all your email messages. See [[http://box.matto.nl/wanderlustgpg.html][GPG and Emacs with Wanderlust]]. This way you can also use [[http://gnupg.org][GnuPG]] (sometimes called openpgp) with GMail.

Happy emailing!
