#+URL: https://www.emacswiki.org/emacs/ProgrammableCompletion
#+AUTHOR: lujun9972
#+DATE: [2017-04-17 一 10:31]
#+TAGS: raw
#+LANGUAGE: zh-CN
#+OPTIONS: H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
EmacsWiki: Programmable Completion

[[https://www.emacswiki.org/emacs/SiteMap]]
[[https://www.emacswiki.org/emacs/SiteMap][SiteMap]]
[[https://www.emacswiki.org/emacs/Search][Search]]
[[https://www.emacswiki.org/emacs/ElispArea][ElispArea]]
[[https://www.emacswiki.org/emacs/HowTo][HowTo]]
[[https://www.emacswiki.org/emacs/Glossary][Glossary]]
[[https://www.emacswiki.org/emacs/RecentChanges][RecentChanges]]
[[https://www.emacswiki.org/emacs/News][News]]
[[https://www.emacswiki.org/emacs/Problems][Problems]]
[[https://www.emacswiki.org/emacs/Suggestions][Suggestions]] 

Search:

Language:

[[https://www.emacswiki.org/emacs?search=%22ProgrammableCompletion%22][ProgrammableCompletion]]


This page is about standard Emacs library `pcomplete.el’ and its related libraries. See
[[https://www.emacswiki.org/emacs/PcompleteExamples][PcompleteExamples]] for examples
of using `pcomplete.el’.

 *Note:* The “programm * /able/ * completion” of library `pcomplete.el’ has nothing to
 do with the “programm * /ed/ * completion” described in the
 [[https://www.emacswiki.org/emacs/EmacsLisp][EmacsLisp]] manual
 ([[http://www.emacswiki.org/cgi-bin/info-ref?find=dynamic-completion-table).]
 [dynamic-completion-table).]] The latter is about using a function to perform completion
 rather than supplying an explicit list of completion candidates.

Adding programmable completion using pcomplete

,* *Write a setup function and add it to your mode’s hook* 

Example: 

(defun pcomplete-erc-setup () 
"Setup erc-mode to use pcomplete." 
(set (make-local-variable 'pcomplete-parse-arguments-function) 
   'pcomplete-parse-erc-arguments) 
(set (make-local-variable 'pcomplete-command-completion-function)  
   'pcomplete/erc-mode/complete-command)
(set (make-local-variable 'pcomplete-command-name-function) 
    'pcomplete-erc-command-name)
(set (make-local-variable 'pcomplete-default-completion-function)
    (lambda () (pcomplete-here (pcomplete-erc-nicks))))
(set (make-local-variable 'pcomplete-suffix-list) '(?  ?:)) 
)                 
(add-hook 'erc-mode-hook 'pcomplete-erc-setup)                                                                                                                                                         

,* *Write the functions that you need* 

 * /pcomplete-parse-arguments-function/ 

pcomplete-parse-arguments-function has no parameters. It returns a list of arguments for
the current command.

,* /pcomplete-command-name-function/ 

Returns the canonical name of the command. This is used to find the appropriate
programmable completion function. For example, if the function returns “MSG” and the
major mode is “erc-mode”, pcomplete will check pcomplete/erc-mode/MSG and
pcomplete/MSG for completions.

,* /pcomplete-default-completion-function/ 

pcomplete-default-completion-function gets called when you don’t have a function for the
command currently being completed. Body should be of the form (pcomplete-here (… list of
completions …))

,* /pcomplete-command-completion-function/ 

Body should be of the form (pcomplete-here (… list of completions …))

-------------------------------------------------------------------------------

[[https://www.emacswiki.org/emacs/CategoryCode][CategoryCode]]
[[https://www.emacswiki.org/emacs/CategoryCompletion][CategoryCompletion]]

-------------------------------------------------------------------------------

[[https://www.emacswiki.org/emacs?action=translate;id=ProgrammableCompletion;missing=de_es_fr_it_ja_ko_pt_ru_se_uk_zh][Add
Translation]]
[[https://www.emacswiki.org/emacs/Comments_on_ProgrammableCompletion][Talk]]
[[https://www.emacswiki.org/emacs?action=edit;id=ProgrammableCompletion][Edit this
page]] [[https://www.emacswiki.org/emacs?action=history;id=ProgrammableCompletion]
[View other revisions]]
[[https://www.emacswiki.org/emacs?action=admin;id=ProgrammableCompletion]
[Administration]]
Last edited 2013-11-01 22:56 UTC by 178-83-148-119.dynamic.hispeed.ch
[[https://www.emacswiki.org/emacs?action=browse;diff=2;id=ProgrammableCompletion]
[(diff)]]
[[https://creativecommons.org/licenses/GPL/2.0/]] 

This work is licensed to you under version 2 of the [[https://www.gnu.org/][GNU]] [[/GPL]
[General Public License]]. Alternatively, you may choose to receive this work under any other
license that grants the right to use, copy, modify, and/or distribute the work, as long as that
license imposes the restriction that derivative works have to grant the same rights and
impose the same restriction. For example, you may choose to receive this work under the
[[https://www.gnu.org/][GNU]] [[/FDL][Free Documentation License]], the
[[https://creativecommons.org/][CreativeCommons]]
[[https://creativecommons.org/licenses/sa/1.0/][ShareAlike]] License, the XEmacs manual
license, or [[/OLD][similar licenses]]. 

Please note our [[Privacy][Privacy Statement]].

