#+TITLE: Emacs with Wanderlust and GMail
#+URL: https://box.matto.nl/emacsgmail.html
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 06月 22日 星期五 15:04:22 CST]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* Emacs with Wanderlust IMAP mailclient
* Emacs与漫游IMAP邮件客户端
:PROPERTIES:
属性:
:CUSTOM_ID: emacs-with-wanderlust-imap-mailclient
:CUSTOM_ID emacs-with-wanderlust-imap-mailclient
:END:
结束:

You have multiple workstations from which you want to approach your email. Maybe because you use both your workstation and your laptop. Or because you want to use email from different locations. Whatever the reason, if you have more than one computer from which you want to have access to your mailboxes, [[http://nl.wikipedia.org/wiki/Internet_Message_Access_Protocol][IMAP]] can provide a good way to get things nicely organized. You could also use a [[http://www.intermedia.net][hosted exchange]] service for extra organization.
您有多个工作站，您想从其中处理您的电子邮件。也许因为你同时使用工作站和笔记本电脑。或者因为你想使用来自不同地方的电子邮件。不管是什么原因，如果您希望从一台以上的计算机访问您的邮箱，[[http://nl.wikipedia.org/wiki/Internet_Message_Access_Protocol][IMAP]]可以提供一种很好的方式来很好地组织事情。您还可以使用[[http://www.intermedia.net][托管exchange]]服务来进行额外的组织。

The [[http://crc.nd.edu/software/xemacs.shtml][IMAP]] protocol let you access your mailboxes, open emails to read without removing the mail from the mailserver. So the next time you log in, your email is still there. (Exept when you deliberately want to delete mail).
[[http://crc.nd.edu/software/xemacs.shtml][IMAP]]协议允许您访问邮箱，打开电子邮件进行阅读，而无需从邮件服务器删除邮件。所以下次你登录时，你的电子邮件还在那里。(除非你想删除邮件)。

Most pop3-mailservers can do IMAP.
大多数pop3-mailserver可以执行IMAP。

To approach an IMAP mailserver from within [[http://en.wikipedia.org/wiki/Emacs][Emacs]], you need to install additional software in Emacs. Wanderlust is an proven solution to add IMAP capabilities to Emacs.
要从[[http://en.wikipedia.org/wiki/Emacs]]内部访问IMAP邮件服务器，您需要在Emacs中安装额外的软件。Wanderlust是向Emacs添加IMAP功能的一个经过验证的解决方案。

* Wanderlust and GMail HOWTO
*漫游指南和GMail指南
:PROPERTIES:
属性:
:CUSTOM_ID: wanderlust-and-gmail-howto
:CUSTOM_ID wanderlust-and-gmail-howto
:END:
结束:

It is very easy to configure Wanderlust to access your [[http://www.gmail.com][GMail]] account.
这是非常容易配置漫游访问您的[[http://www.gmail.com][GMail]]帐户。

Here are the steps to do so:
以下是具体的步骤:

1. Get wanderlust
1. 有漫游癖
2. Create ~/.folders
2. 创建~ / .folders
3. Append the wanderlust configuration to ~/.emacs
3.将漫游欲望配置附加到~/.emacs
4. Start emacs, start wanderlust and enjoy the most effecient and effective GMail client in the world
4. 启动emacs，启动漫游癖，享受世界上最有效的GMail客户端

** Get wanderlust
* *有漫游癖
:PROPERTIES:
属性:
:CUSTOM_ID: get-wanderlust
:CUSTOM_ID get-wanderlust
:END:
结束:

#+BEGIN_EXAMPLE
apt-get install wl
#+END_EXAMPLE

If you don't have Debian, this is where you can find [[http://www.gohome.org/wl/][Wanderlust]]
如果你没有Debian，你可以在这里找到[[http://www.gohome.org/wl/][Wanderlust]]

** Create ~/.folders
* *创建~ / .folders
:PROPERTIES:
属性:
:CUSTOM_ID: create-.folders
:CUSTOM_ID:创建-.folders
:END:
结束:

If you don't have Debian, this is where you can find [[http://www.gohome.org/wl/][Wanderlust]]
如果你没有Debian，你可以在这里找到[[http://www.gohome.org/wl/][Wanderlust]]

This is the minimal content of ~/.folders:\

#+BEGIN_EXAMPLE
%inbox "inbox"
+trash "Trash"
+draft "Drafts"
#+END_EXAMPLE

** Append the wanderlust configuration to ~/.emacs
**将漫游配置附加到~/.emacs
:PROPERTIES:
属性:
:CUSTOM_ID: append-the-wanderlust-configuration-to-.emacs
:CUSTOM_ID append-the-wanderlust-configuration-to . emacs
:END:
结束:

Put this in your ~/.emacs:
把这个写进你的~/.emacs:

#+BEGIN_EXAMPLE
;; wanderlust
(autoload 'wl "wl" "Wanderlust" t)
(autoload 'wl-other-frame "wl" "Wanderlust on new frame." t)
(autoload 'wl-draft "wl-draft" "Write draft with Wanderlust." t)

;; IMAP
(setq elmo-imap4-default-server "imap.gmail.com")
(setq elmo-imap4-default-user "<accountname>@gmail.com")
(setq elmo-imap4-default-authenticate-type 'clear)
(setq elmo-imap4-default-port '993)
(setq elmo-imap4-default-stream-type 'ssl)

(setq elmo-imap4-use-modified-utf7 t)

;; SMTP
(setq wl-smtp-connection-type 'starttls)
(setq wl-smtp-posting-port 587)
(setq wl-smtp-authenticate-type "plain")
(setq wl-smtp-posting-user "mattofransen")
(setq wl-smtp-posting-server "smtp.gmail.com")
(setq wl-local-domain "gmail.com")

(setq wl-default-folder "%inbox")
(setq wl-default-spec "%")
(setq wl-draft-folder "%[Gmail]/Drafts") ; Gmail IMAP
(setq wl-trash-folder "%[Gmail]/Trash")

(setq wl-folder-check-async t)

(setq elmo-imap4-use-modified-utf7 t)

(autoload 'wl-user-agent-compose "wl-draft" nil t)
(if (boundp 'mail-user-agent)
(setq mail-user-agent 'wl-user-agent))
(if (fboundp 'define-mail-user-agent)
(define-mail-user-agent
'wl-user-agent
'wl-user-agent-compose
'wl-draft-send
'wl-draft-kill
'mail-send-hook))
#+END_EXAMPLE

** Start emacs, start wanderlust and enjoy the most effecient
**启动emacs，启动漫游，享受最有效
and effective GMail client in the world
和有效的GMail客户在世界各地
:PROPERTIES:
属性:
:CUSTOM_ID: start-emacs-start-wanderlust-and-enjoy-the-most-effecient-and-effective-gmail-client-in-the-world
:CUSTOM_ID start-emacs-start-wanderlust-and-enjoy-the-most-effecient-and-effective-gmail-client-in-the-world
:END:
结束:

Start emacs and do
启动emacs并执行

#+BEGIN_EXAMPLE
M-x wl
#+END_EXAMPLE

\
Now you will be prompted for your gmail password. After this, you can access your gmail inbox.
现在将提示您输入gmail密码。在此之后，您可以访问您的gmail收件箱。

Now you will be prompted for your gmail password. After this, you can access your gmail inbox.
现在将提示您输入gmail密码。在此之后，您可以访问您的gmail收件箱。

If you want to open other mailboxes besides inbox you should add them to your ~/.folders (I have not tested this).
如果你想打开除收件箱之外的其他邮箱，你应该把它们添加到~/中。文件夹(我还没有测试这个)。

You can send email through your gmail account to. Create a new mail in Wanderlust and send it. You will be prompted for your password again and your mail is sent.
您可以通过您的gmail帐户发送电子邮件到。在“漫游癖”中创建一个新邮件并发送它。系统会再次提示您输入密码，然后发送邮件。

* Encrypt your messages
*加密你的讯息
:PROPERTIES:
属性:
:CUSTOM_ID: encrypt-your-messages
:CUSTOM_ID encrypt-your-messages
:END:
结束:

It is a good habit to encrypt all your email messages. See [[http://box.matto.nl/wanderlustgpg.html][GPG and Emacs with Wanderlust]]. This way you can also use [[http://gnupg.org][GnuPG]] (sometimes called openpgp) with GMail.
把你所有的电子邮件都加密是个好习惯。看到[[http://box.matto.nl/wanderlustgpg。[GPG和Emacs与漫游欲望]]。通过这种方式，您还可以使用[[http://gnupg.org][GnuPG]](有时称为openpgp)和GMail。

Happy emailing!
发邮件快乐!
