#+TITLE: Firefox and org-protocol URL Capture
#+URL: http://www.mediaonfire.com/blog/2017_07_21_org_protocol_firefox.html
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2019年 02月 26日 星期二 16:41:35 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil


* Introduction

As an *Emacs* guy, I attempt to force all my workflow into [[http://orgmode.org/][org-mode]] -- for me life is better in text.

I tend to prefer to store bookmarks in [[http://orgmode.org/][org-mode]] todo lists, and [[http://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol]] allows external processes to interact with some of [[http://orgmode.org/][org-mode's]] features. Setup, though, is an hassle. There are plenty of tutorials out there ([[https://duckduckgo.com/?q=org-protocol+firefox&t=ffab&ia=qa][search]]), and there are Firefox [[https://addons.mozilla.org/en-US/firefox/search/?q=org-protocol&cat=1,0&appver=53.0&platform=linux][extensions]], but overall I've not had great luck with them.

I therefore decided to put my current setup in this blog post as another data point for those trying to get it all working.

* Setup your Emacs Org Mode Configuration

Enable =org-protocol=:

#+BEGIN_EXAMPLE
    (require 'org-protocol)
#+END_EXAMPLE

Add a capture template - here's mine:

#+BEGIN_EXAMPLE
    (setq org-capture-templates
     (quote (...
     ("w" "org-protocol" entry (file "~/org/refile.org")
     "* TODO Review %a\n%U\n%:initial\n" :immediate-finish)
     ...)))
#+END_EXAMPLE

The [[http://orgmode.org/manual/Capture-templates.html][capture templates]] section in the [[http://orgmode.org][org-mode]] manual will help.

Add the default template to use:

#+BEGIN_EXAMPLE
    (setq org-protocol-default-template-key "w")
#+END_EXAMPLE

Eval those additions so they're active in your current *Emacs* session.

* A Quick Test

Before going further, it's a good idea to test your configuration:

#+BEGIN_EXAMPLE
    emacsclient -n "org-protocol:///capture?url=http%3a%2f%2fduckduckgo%2ecom&title=DuckDuckGo"
#+END_EXAMPLE

This should pop open a capture window based on the template you added. Until this works, no point in going forward. If it doesn't work, go back through the configuration above and ensure that you've eval'd the code blocks.

If you have an old version of [[http://orgmode.org/][org-mode]] (older than 7, I believe), the format is different: the urlencoded form is replaced by slashes as separators of the url and title. A quick search will show you the difference.

* Firefox Protocol

Now to setup Firefox. Browse to *about:config*. Right-click on the list of configuration items, choose *New* -> *Boolean*, and enter =network.protocol-handler.expose.org-protocol= for the name and toggle the value to *true*.

Some tutorials indicate this step is optional -- YMMV.

* Add Desktop File

Most of the tutorials include this:

Add =~/.local/share/applications/org-protocol.desktop=:

#+BEGIN_EXAMPLE
    [Desktop Entry]
    Name=org-protocol
    Exec=/path/to/emacsclient -n %u
    Type=Application
    Terminal=false
    Categories=System;
    MimeType=x-scheme-handler/org-protocol;
#+END_EXAMPLE

Then run your updater. For =i3= I use (same as for =gnome=):

#+BEGIN_EXAMPLE
    update-desktop-database ~/.local/share/applications/
#+END_EXAMPLE

KDE has a different method... again some of the tutorials for getting *org-protocol* working can help.

* Setup Capture Button in Firefox

Create a bookmark (I create it in the toolbar) with the following "Location":

#+BEGIN_EXAMPLE
    javascript:location.href="org-protocol:///capture?url="+encodeURIComponent(location.href)+"&title="+encodeURIComponent(document.title||"[untitled page]")
#+END_EXAMPLE

After you save it, should you edit the bookmark, expect to see any spaces replaced by '%20' -- the url encoding for a "space".

Now when you click the bookmark, you should get a window opened in an *Emacs* frame, any random frame, showing your template.
