#+TITLE: Getting started with Magit (Or what I hope I could've read when I first tried out Magit)
#+URL: https://kisaragi-hiu.com/blog/2018-09-20-magit-introduction/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2018年 10月 19日 星期五 12:44:17 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
This is a quick guide for using [[https://magit.vc/][Magit]], a wonderful Git interface based in Emacs. Its base features are fairly simple, but it can be confusing if you're not already using Emacs, as I was a few months ago.
这是一个使用[[https://magit的快速指南。[Magit]]，一个很好的基于Emacs的Git接口。它的基本特性相当简单，但是如果您还没有像几个月前那样使用Emacs，就会感到困惑。

[[https://kisaragi-hiu.com/videos/emacs-magit-typical-workflow.mp4]]
[[https://kisaragi-hiu.com/videos/emacs-magit-typical-workflow.mp4]]

** The =magit= command
** =magit=命令
:PROPERTIES:
属性:
:CUSTOM_ID: the-magit-command
:CUSTOM_ID the-magit-command
:END:
结束:

I'll explain Emacs basics in the last paragraph.
我将在最后一段解释Emacs的基础知识。

The stage / committing workflow with Magit is centered around an interactive version of =git status=.
使用Magit的阶段/提交工作流以交互式版本=git status=为中心。

Call =magit= in a git repository, ie. when you have a file or folder open in the repo. The window that pops up is that interactive =git status=.
在git仓库中调用=magit=。当您在repo中打开一个文件或文件夹时。弹出的窗口是interactive =git status=。

[[https://kisaragi-hiu.com/videos/emacs-magit-status.mp4]]
[[https://kisaragi-hiu.com/videos/emacs-magit-status.mp4]]

Move the cursor onto a hunk and press =Tab=. This toggles display of its contents. Press =s= to stage, =u= to unstage, =c= for commit options, =F= for pulling options, and =P= for pushing options.
将光标移动到一个物体上，然后按=Tab=。这将切换其内容的显示。按=s= to stage， =u= to unstage， =c= for commit options， =F= for pull options， =P= for push options。

This alone, I feel, is many times faster than using =git status=, =git diff=, =git add=, =git commit=, etc. directly.
我觉得这比直接使用=git status=、=git diff=、=git add=、=git commit=等要快很多倍。

Pressing =Enter= will visit the hunk under cursor.
按下=回车=将会访问光标下的大块。

Also check out other options in the “Magit” menu located in the menu bar, when you're in the Magit window.
当你在Magit窗口时，也可以查看位于菜单栏中的“Magit”菜单中的其他选项。

[[https://kisaragi-hiu.com/videos/emacs-magit-quick-workflow.mp4]]
[[https://kisaragi-hiu.com/videos/emacs-magit-quick-workflow.mp4]]

** Setting up Magit (and Emacs)
**设置Magit(和Emacs)
:PROPERTIES:
属性:
:CUSTOM_ID: setting-up-magit-and-emacs
:CUSTOM_ID setting-up-magit-and-emacs
:END:
结束:

If you have an Emacs configuration already, just install Magit from MELPA and ignore this.
如果您已经有了Emacs配置，只需从MELPA安装Magit并忽略它。

This will introduce Emacs package management with =use-package=, in a way that I think is easier to maintain.
这将介绍使用=use-package=进行Emacs包管理，我认为这种方式更容易维护。

Edit the file =~/.emacs.d/init.el=, then type this into it:
编辑文件=~/.emacs.d/init。el=，然后把这个输入:

#+BEGIN_EXAMPLE
(require 'package)
;; load packages ourselves
;; press C-h v on the variable for more documentation
(setq package-enable-at-startup nil)
;; Add MELPA to package-archives
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
;; load packages now
(package-initialize)

;; Emacs adds `custom' settings in the init file by default. Run this file
;; without this segment to see what that means.
;; Put those away in "custom.el".
(setq custom-file (concat user-emacs-directory "custom.el"))
(load custom-file :noerror)

;; update local database then install use-package if it's not installed
(unless (package-installed-p 'use-package)
(package-refresh-contents)
(package-install 'use-package))

(require 'use-package)
;; tell use-package to install a package if it's not already installed
(setq use-package-always-ensure t)
#+END_EXAMPLE

Then install Magit and set a keyboard shortcut to invoke it:
然后安装Magit并设置键盘快捷键来调用它:

#+BEGIN_EXAMPLE
(use-package magit
:bind (("C-x g" . magit)))
#+END_EXAMPLE

Read more about Magit in its manual. [[https://magit.vc/manual/magit/]]
阅读更多关于Magit的手册。[[https://magit.vc/manual/magit/]]

** Emacs basics
* * Emacs的基础
:PROPERTIES:
属性:
:CUSTOM_ID: emacs-basics
:CUSTOM_ID emacs-basics
:END:
结束:

The mouse can be used for selection or moving the cursor around, like other editors. Typing something with an active selected region by default does not replace the text; to enable the expected behavior, add =(delete-selection-mode 1)= to your init file. A selected region is just called a “region” in Emacs.
与其他编辑器一样，鼠标可用于选择或移动光标。在默认情况下，用活动的选定区域输入内容并不会替换文本;要启用预期的行为，请在init文件中添加=(删除-选择模式1)=。选定的区域在Emacs中称为“区域”。

Arrow keys work as expected, and you can explore other more efficient movement keys in the Emacs tutorial; start it with
箭头键工作正常，您可以在Emacs教程中探索其他更有效的移动键;开始用
C-h t, or run
C-h - t，或者run
M-x =help-with-tutorial=.
m x = help-with-tutorial =。
