#+URL: http://endlessparentheses.com/markdown-style-link-ids-in-org-mode.html

Link handling and exporting is one of the most versatile aspects of org-mode.
Did you know you can make org-mode understand Markdown style link IDs?

You should already know [[http://endlessparentheses.com/use-org-mode-links-for-absolutely-anything.html][org-links can do absolutely anything]], but it takes a
little creativity to know how to apply that. [[http://emacs.stackexchange.com/q/594/50][Here's the question]] by Kaushal
that prompted this over at [[http://emacs.stackexchange.com/][Emacs.StackExchange]].

#+BEGIN_QUOTE
    At times, I need to use the same link at multiple places in a long
    document. For those cases it would be useful to have link IDs like in
    markdown.
   
    This is [an example][some-id] reference-style link. 
    
    Then, anywhere in the document, you define your link label like this, on a
    line by itself:
   
     [some-id]: http://example.com/
#+END_QUOTE
    
[[http://emacs.stackexchange.com/a/599/50][The solution]] I came up with defines three different functions, so I’ll let you
follow the link instead of clogging up this blog post. The result is that you
can define link IDs like this anywhere in your document (probably the top or
the bottom).

#+BEGIN_SRC org
  ,#+LINK-ID: wiki http://www.emacswiki.org
#+END_SRC

And then you can use that URL in links throughout the document by writing them
like this.

#+BEGIN_SRC org
  Here is a [[lid:wiki][wiki link]], and here 
  is [[lid:wiki][another one]].
#+END_SRC
