#+TITLE: Org-mode_For_PHD_Students
#+URL: http://matthieu.io/blog/2016/10/22/org-mode-phd/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2016-10-29 六 14:25]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil



I've discovered [[http://orgmode.org/][org-mode]] more or less when I began my PhD, and found it to be a really valuable tool to keep track of everything I do. Here are my tips on how I manage my work with orgmode, file by file:

* research.org

I keep track of the list of papers I'm currently writing, each of them having their TODOs, their deadlines, and so on. I also use this file to keep track of the random research ideas I get and am afraid to
forget.

Bonus: keep the experiments recipes in embedded code in orgmode, for reproducible research purposes.

* teaching.org

Here I have everything that relates to teaching: all my classes organized by year and semester, with my notes, the list of students, and all the information I receive by email that would otherwise get lost.

Bonus: write class slides in orgmode.

* readings.org

This one is simple: it contains a list of all the papers I've read, with my notes and the date I read them. I suspect it will become very valuable once I write my actual thesis.

Bonus: keep links to the local PDFs, for faster access.

* learning.org

All the courses and seminars I attend, with my notes. Also useful to not forget to actually attend them. This way I can easily keep track of my ECTS (European class credits) and I can know if I still miss some
to be allowed to defend my thesis at the end.

* meetings.org

Every meeting I attend, along with my meeting notes.

Bonus: set-up recurrent events for meeting your PhD supervisor.

* backlog.org

This one contains the miscellaneous items (often administrative tasks) that I need to do and rather not forget about it. Very useful to set-up deadlines far ahead in the future!

* travels.org

All the information I need to keep when traveling, for example to conferences. Also good for remembering when I went to some place.

* All in all

I also use a few other .org files, but the ones listed below are those which track my PhD student life. I also have a projects.org to keep random ideas that I will never implement (but will be fun to look at
in a few years!), a writings.org (where I'm typing this post draft right now), etc. I make an extensive use of timestamps along with my TODO items, to be sure not to forget paper submission deadlines and other
important dates.

If you have a different setup or tips to improve mine, I'd be very glad to hear from you!
