#+TITLE: Org-mode_For_PHD_Students
#+URL: http://matthieu.io/blog/2016/10/22/org-mode-phd/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2016-10-29 六 14:25]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil



我差不多是在开始读博士的时候接触到的 [[http://orgmode.org/][org-mode]] , 我发现用它真是一件很棒的工具，我可以用它我追踪我做过的每一件事情. 下面我就来说说我是怎么用orgmode来管理自己的工作的,让我们一个文件一个文件地说:

* research.org

我用这个文件来追踪那些在读的论文, 每篇论文都有独立的代办事情，截止日期等内容. 我也会把一些偶尔想到的idea记在这里以防忘掉了.

好处: 可以将实验步骤记录在orgmode的内嵌代码块中，这样可以重现研究过程了.

* teaching.org

这里存放的关于教学方面的内容: 里面按年份和学习组织了我要教的课程，相关的笔记，上课的学生，以及电子邮件中的相关信息.

好处: 可以用org模拟幻灯片

* readings.org

这个文件存的东西很简单: 它里面存放的所有我读过的论文,相关的笔记以及读完的日期. 这在我写论文时非常有用.

好处: 可以建立链接连接到本地的PDF文件，可以快速的访问这些文件.

* learning.org

我参加过的所有课程及其我记录的相关笔记. 同时也是提醒我不要忘了上课. 这样一来我可以很方便的追踪我的ECTS (European class credits)情况， 

and I can know if I still miss some to be allowed to defend my thesis at the end.

* meetings.org

我参加过的所有会议以及相关记录.

好处: 可以设置循环任务来提醒我与博士导师见面.

* backlog.org

里面存的是那些杂项事物 (一般是那些管理性的任务). 设置deadline的功能相当有用!

* travels.org

All the information I need to keep when traveling, for example to conferences. Also good for remembering when I went to some place.

* All in all

I also use a few other .org files, but the ones listed below are those which track my PhD student life. I also have a projects.org to keep random ideas that I will never implement (but will be fun to look at
in a few years!), a writings.org (where I'm typing this post draft right now), etc. I make an extensive use of timestamps along with my TODO items, to be sure not to forget paper submission deadlines and other
important dates.

If you have a different setup or tips to improve mine, I'd be very glad to hear from you!
