#+TITLE: Setting up Ediff · (or emacs
#+URL: https://oremacs.com/2015/01/17/setting-up-ediff/
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2020年 02月 14日 星期五 12:29:08 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
* Setting up Ediff
  :PROPERTIES:
  :CUSTOM_ID: setting-up-ediff
  :CLASS: post-title
  :END:

Once you make Ediff bearable, it becomes wonderful. At least this was my experience. It's a very good tool, but some of the defaults look very poor to me.

** Customizing the =customize=
   :PROPERTIES:
   :CUSTOM_ID: customizing-the-customize
   :END:

First of all, I'll list a macro that I've started to use for setting custom variables:

#+BEGIN_EXAMPLE
  (defmacro csetq (variable value)
   `(funcall (or (get ',variable 'custom-set)
   'set-default)
   ',variable ,value))
#+END_EXAMPLE

This macro I've put together myself after searching though the code base and not finding something similar; =custom-set-variables= comes close to what I want, or maybe =custom-initialize-changed=. Basically all I want is a =setq= that is aware of the =custom-set= property of a variable. If you know such a macro, please let me know.

** Changing some Ediff options
   :PROPERTIES:
   :CUSTOM_ID: changing-some-ediff-options
   :END:

Now, that I've explained the custom setter (by the way, using =custom-set-variables= is absolutely equivalent to =csetq=), here are my changes:

1. Don't use the weird setup with the control panel in a separate frame. I can manage windows in Emacs much better than my desktop (Unity or Gnome Shell) can manage the Emacs frames.

   #+BEGIN_EXAMPLE
     (csetq ediff-window-setup-function 'ediff-setup-windows-plain)
   #+END_EXAMPLE

2. Split the windows horizontally instead of vertically. This way, it's much easier to follow the changes.

   #+BEGIN_EXAMPLE
     (csetq ediff-split-window-function 'split-window-horizontally)
   #+END_EXAMPLE

3. Ignore white space. I don't write a lot of Python, so I don't care about the white space in the diffs. At the same time, I re-format any LISP code that I edit to my liking, and I want to see only the important changes in the diff, and not the whitespace nonsense.

   #+BEGIN_EXAMPLE
     (csetq ediff-diff-options "-w")
   #+END_EXAMPLE

** Changing some Ediff key bindings
   :PROPERTIES:
   :CUSTOM_ID: changing-some-ediff-key-bindings
   :END:

This is just the standard stuff that I like to do for each mode that does not self-insert: assign j to move down, and k to move up.

#+BEGIN_EXAMPLE
  (defun ora-ediff-hook ()
   (ediff-setup-keymap)
   (define-key ediff-mode-map "j" 'ediff-next-difference)
   (define-key ediff-mode-map "k" 'ediff-previous-difference))

  (add-hook 'ediff-mode-hook 'ora-ediff-hook)
#+END_EXAMPLE

** Restoring the windows after Ediff quits
   :PROPERTIES:
   :CUSTOM_ID: restoring-the-windows-after-ediff-quits
   :END:

When you quit an Ediff session with q, it just leaves the two diff windows around, instead of restoring the window configuration from when Ediff was started. Here's the (slightly hacky) code to restore the old window configuration:

#+BEGIN_EXAMPLE
  (winner-mode)
  (add-hook 'ediff-after-quit-hook-internal 'winner-undo)
#+END_EXAMPLE

** List of ways that I use to invoke Ediff
   :PROPERTIES:
   :CUSTOM_ID: list-of-ways-that-i-use-to-invoke-ediff
   :END:

*** from =magit=
    :PROPERTIES:
    :CUSTOM_ID: from-magit
    :END:

In 80% of the cases, I call Ediff with e (=magit-ediff=) from =magit-status-mode=. This gives me a better overview of the changes, especially when I want to revert stuff with either a (=ediff-copy-A-to-B=) or b (=ediff-copy-B-to-A=). Probably with a, since [[https://github.com/magit/magit][magit]] seems to consistently put the =@{index}= file into the =A= diff window, and the current file into the =B= window.

So if I'm looking at a diff (to which I navigated with j/k), I can revert it with a. At this point, the diff region in the current file will become equal to that of the index file. But it will not be saved yet. If I want to save the current file in the =B= window, I can do it with wb (=ediff-save-buffer=). After a revert, it's also useful to call !(=ediff-update-diffs=), which will remove the zero-length diffs and update the diff-count in the mode-line.

*** other methods
    :PROPERTIES:
    :CUSTOM_ID: other-methods
    :END:

1. =ediff-buffers= will diff two (different) buffers. If you happen to have only two windows open with the appropriate buffers, you get them as defaults and can choose them quickly with RET RET.
2. =ediff-files= is similar, but works on files instead. I like to just mark the appropriate files in =dired= with m, then they also get auto-selected by =ediff-files=.
3. =ediff-current-file= is useful to see the unsaved changes to the current file. I rarely use it, since I have a compulsion to save every file every chance I get. There is little hope to recover from this addiction, unless someone implements an analogue of [[https://github.com/bbatsov/guru-mode][guru-mode]] that annoys you when you try to save a file. Actually, it's not a bad idea - C-x C-s:

#+BEGIN_QUOTE
  Oleh, you have saved this file =40 times= in the last hour; the last
  save was =0 minutes 34 seconds ago=; since then, you've changed =27 bytes= of information. Are you *sure* you want to save =[y/N]=?
#+END_QUOTE
