#+TITLE: The Power of Emacs: Developing Websites in Real-time with Impatient Mode
#+URL: https://dev.to/avocadoras/the-power-of-emacs-developing-websites-in-real-time-with-impatient-mode-33fh
#+AUTHOR: lujun9972
#+TAGS: raw
#+DATE: [2019年 02月 11日 星期一 15:36:45 HKT]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t n:nil ::t |:t ^:nil -:nil f:t *:t <:nil
Do you ever find yourself editing HTML or CSS files but would like to see your browser render changes in real-time? Emacs offers an easy solution to this problem, provided you have Emacs GUI installed via =apt-get install emacs=, =pacman -Syu emacs= or =brew cask install emacs=. Once you have Emacs set up you will need to install =impatient-mode= package via MELPA. I will leave you with a link to my [[https://github.com/avocadoras/.emacs.d.git][emacs configuration]] so you can follow along in this tutorial without having any knowledge of Emacs or how to setup packages with MELPA.
你曾经发现自己编辑HTML或CSS文件，但希望看到你的浏览器呈现实时变化吗?Emacs为这个问题提供了一个简单的解决方案，只要您通过=apt-get install Emacs =， =pacman -Syu Emacs =或=brew cask install Emacs =安装Emacs。设置Emacs之后，需要通过MELPA安装=impatient-mode= package。我将给您留下一个链接，链接到我的[[https://github.com/avocadoras/.emacs.d.git][emacs配置]]，这样您就可以在不了解emacs或如何使用MELPA设置包的情况下继续学习本教程。

* Install emacs
*安装emacs
:PROPERTIES:
属性:
:CUSTOM_ID: install-emacs
:CUSTOM_ID install-emacs
:END:
结束:

These steps should work on any platform that runs Emacs. Emacs comes pre-installed in many *nix distributions, but you may need to first install Emacs GUI from your system's package repository.
这些步骤应该适用于任何运行Emacs的平台。Emacs预装在许多*nix发行版中，但是您可能需要首先从系统的包存储库中安装Emacs GUI。

- Open your terminal
-开启终端机
- in your prompt type =$ brew cask install emacs=, =$ pacman -Syu emacs= or =$ apt-get install emacs=
-在你的提示类型=$ brew cask安装emacs=， =$ pacman - syu emacs=或=$ apt-get安装emacs=

* Install impatient mode in Emacs
*在Emacs中安装不耐烦模式
:PROPERTIES:
属性:
:CUSTOM_ID: install-impatient-mode-in-emacs
:CUSTOM_ID install-impatient-mode-in-emacs
:END:
结束:

This step requires that you set up Emacs with MELPA and that you configure it in your =init.el= file in =.emacs.d/= and then install =impatient-mode= Emacs package. Thankfully, you don't need to figure this out if you copy my emacs configuration to your =.emacs.d/= directory.
此步骤要求您使用MELPA设置Emacs，并在=init中配置它。el= file in =.emacs。d/=，然后安装=impatient-mode= Emacs包。值得庆幸的是，如果您将我的emacs配置复制到您的=.emacs，则不需要解决这个问题。d / =目录。

- make sure you are in your =$HOME= directory by typing =cd ~=
-通过键入=cd ~=确保您在=$HOME=目录中
- run =$ git clone https://github.com/avocadoras/.emacs.d.git=
-运行=$ git克隆https://github.com/avocadoras/.emacs.d.git=

You can =cd= into the repository after it finishes cloning.
在完成克隆之后，可以将=cd=放入存储库。

* Optional: Switch to web-impatient branch
*可选:切换到web-分支
:PROPERTIES:
属性:
:CUSTOM_ID: optional-switch-to-web-impatient-branch
:CUSTOM_ID optional-switch-to-web-impatient-branch
:END:
结束:

My personal configuration contains many packages that will slow down Emacs launch. If you start Emacs from scratch you will need to set up MELPA with Emacs and then install Impatient Mode. To reduce headaches you can copy my emacs configuration and switch to the branch =web-impatient=. This branch will launch Emacs quicker than with my personal configuration.
我的个人配置包含许多会减慢Emacs启动的包。如果您从头开始Emacs，您将需要使用Emacs设置MELPA，然后安装急躁模式。为了减少麻烦，您可以复制我的emacs配置并切换到branch =web- =。这个分支将比我的个人配置更快地启动Emacs。

- make sure you are in =.emacs.d/= by typing in your terminal prompt =$ cd .emacs.d/=
-确保你在=.emacs。d/=输入您的终端提示=$ cd .emacs.d/=
- switch to web-impatient branch by typing =$ git checkout web-impatient=
-通过输入=$ git签出web- =切换到web-分支

* Tell Emacs to open any HTML file
*告诉Emacs打开任何HTML文件
:PROPERTIES:
属性:
:CUSTOM_ID: tell-emacs-to-open-any-html-file
:CUSTOM_ID tell-emacs-to-open-any-html-file
:END:
结束:

You will need to open the file with Emacs so switch to a directory in your filesystem that contains an HTML file or open and create a new one by typing =$ emacs test.html=
您将需要使用Emacs打开文件，因此切换到文件系统中包含HTML文件的目录，或者通过键入=$ Emacs test.html=创建一个新目录

* Start up a http server and run impatient mode in your file
*启动http服务器并在文件中运行不耐烦模式
:PROPERTIES:
属性:
:CUSTOM_ID: start-up-a-http-server-and-run-impatient-mode-in-your-file
:CUSTOM_ID start-up-a-http-server-and-run-impatient-mode-in-your-file
:END:
结束:

You will need to start the http server that comes with =impatient-mode= package by typing in your file =ALT-x httpd-start= (in macOS this would be =OPTION-x httpd-start=) then hit the key =RETURN= or =ENTER=. Then you will need to activate =impatient-mode= by typing =ALT-x impatient-mode=(=OPTION-x impatient-mode=) then hit the key =RETURN= or =ENTER=.
您需要通过在文件中键入=ALT-x httpd-start=(在macOS中这应该是=OPTION-x httpd-start=)来启动与=impatient-mode= package一起提供的http服务器，然后按下键=RETURN= or =ENTER=。然后您需要通过键入=ALT-x impatient-mode=(=OPTION-x impatient-mode=)来激活=impatient-mode=，然后按下键=RETURN=或=ENTER=。

* Browse localhost:8080/imp/test.html and type your html file in Emacs
*浏览localhost:8080/imp/test.html，然后在Emacs中输入你的html文件
:PROPERTIES:
属性:
:CUSTOM_ID: browse-localhost8080imptest.html-and-type-your-html-file-in-emacs
:CUSTOM_ID browse-localhost8080imptest.html-and-type-your-html-file-in-emacs
:END:
结束:

You will need to first launch your browser and go to the address in localhost where your file is served. The address should be =http://localhost:8080/imp=. You will see a list served files. Click the file you want rendered. Finally, type anything in your =test.hml= file and your browser will start rendering anything you type.
您将需要首先启动浏览器并转到提供文件的localhost地址。地址应该是=http://localhost:8080/imp=。您将看到一个已服务的文件列表。单击要呈现的文件。最后，在=test中键入任何内容。hml=文件，您的浏览器将开始呈现您键入的任何内容。

* DEMO
*演示
:PROPERTIES:
属性:
:CUSTOM_ID: demo
:CUSTOM_ID:演示
:END:
结束:

[[https://youtu.be/YSU4FF5gTiY]]
[[https://youtu.be/YSU4FF5gTiY]]
