#+TITLE: 是否值得学习GNU--陈斌的回答
#+URL: https://www.quora.com/Is-it-worth-learning-gnus-for-emacs/answer/Chen-Bin-3?srid=H9Il&share=7b1a5984 
#+AUTHOR: lujun9972
#+CATEGORY: raw
#+DATE: [2016-07-25 一 17:32]
#+OPTIONS: ^:{}

* [[https://www.quora.com/Is-it-worth-learning-gnus-for-emacs][Is it worth learning gnus for emacs?]]

I currently use emacs for all my text editing & coding and love it, but for reading news/blogs/twitter & for
gmail, I still use web interfaces. I dipped my toe into using gnus, but I'd like to know what the payoff is
before investing the time---it seems to have less clear value proposition & it seems complex.
UpdateCancel

* 陈斌的回答

Yes, check my [[http://blog.binchen.org/?p=403][Practical guide to use Gnus with Gmail]]

Reasons to use Gnus
=================
1. less overhead to send email, Just press "C-x m" anywhere to send new email
2. Mark all emails read is easier than Gmail web UI.
3. attach file and forward multiple emails are really handy
4. Other emacs plugins are also useful for writing email.

Please note
=========
1. I don't read newsgroups or mailing list
2. I still use Gmail web UI sometimes.
3. Gnus support read html email by combining with w3m
4. You can write html email by combining with org-mode and org-mime (it's
especially good at writing email containing html table"

Key point to use Gnus
==================
This part is important, because even you are persuaded by me. It's 99% possible you will give up after the
first try!

Gnus by default will hide some emails, or groups in certain situation, too smart, eh? Most user cannot
overcome this because they don't know why their email is missing.

For example, say your happily open Gnus and find 10 new emails in your INBOX folder. you read all of them and
forget them. Then after an hour, your boss remind you that one of the email is very important so he need
review the email together with you. You open the Gnus and find INBOX folder is GONE! Gnus by default will hide
folder who containing NO unread emails! BTW, Gmail has similar feature but is not turned on by default.

If you bother reading manual (I do, I spent 5 hours to read manual), you will find its manual a bit difficult
to understand.

Anyway, I bite the bullet and finish the manual, now I totally understand.

The key point is tell gnus SHOW EVERYTHING:
1. check my guide for detailed set up
2. when you open INBOX folder which has ZERO unread emails, press C-u and Enter instead of Enter if you want
to see ALL the emails.

Tips
====
1. yasnippet is really cool when you need write similar emails daily (replying to job agents, for example).
2. press c to mark all the email in inbox READ is really handy (Gmail's own interface sucks)
3. search, filter (in gnus it's called limit) email is good (search is not as handy as gmail,but filter is
much better)
4. you can install another software called popfile to categorize your email, it's much much much better than
google's own (filter rules or their auto-labelling)
5. Attach files in email is efficient in Gnus (1 or 2 seconds)
6. Forward email or attach email is easy
7. you can use another software called davmail to get email (please use pop3 instead of imap because gnus has
some bug) from outlook exchange server. And don't forget keep the copy on server because you are using POP3!
8. reading html email is easy, just use emacs-w3m
9. writing html email is actually much more efficient than other softwares., just use org-mime, especially
when you want to create html tables, which could be ten times faster.

check my ~/.emacs.d at [[http://github.com/redguardtoo/emacs.d][redguardtoo/emacs.d]] if you need details.
