#+TITLE: Org-mode与Hyperbole之间的区别
#+AUTHOR: lujun9972
#+URL: https://lists.gnu.org/archive/html/emacs-devel/2016-06/msg00246.html                                 
#+CATEGORY: org-mode
#+DATE: [2016-08-08 周一 14:36]
#+OPTIONS: ^:{}


虽然从表面上来看这两者很接近,但是一旦你开始使用这两者,你很快就能发现其中的不同点. 现在它们是完全不一样的,也许以后会有一些交集吧.

Org-mode是一个基于结构化文件的major-mode,它是建立在Emacs的outlinning mode之上的.
Hyperbole是一个整合Emacs各项功能的一个系统,它提供了随处可及的快捷键以及hyperbuttons.

Org-mode的大纲就是Emacs的普通的大纲.
Hyperbole的Koutliner是有唯一性的; 每个节点/段落都有唯一的一个id以及相应的属性. 当你修改大纲时,节电/段落的id也会自动更像,你可以很清楚的知道id为2b4的节点就是id为2b的节点的子节点,同时也是id为2b3节点的兄弟节点.

Org-mode需要你明确的创建一个超链接.
Hyperbole这有这项功能,只需要在不同的window之间用鼠标一拖,就能在任意类型的文本文件中创建超链接.
但是Hyperbole同时还能识别内嵌于多种类型的文件或buffer中的超链接. 而且它也很容易扩展支持新的超链接类型. 你只需要按下一个按钮,Hyperbole就会在相关的上下文环境中作该做的事情.

Org-mode可以管理待办,计时以及一些基础的项目管理功能.
Hyperbole并没有相关的功能,但是它可以与你喜欢的待办管理功能相整合.

Org-mode据我所做是没有联系人管理功能的(不是很确定因为我没有用过相关功能).
Hyperbole有一个快速而有效率的分级联系人管理器.

Org-mode只是个major-mode而已,因此它不会去修改你的buffers, windows 以及frames.
Hyperbole有一个快速的,经过仔细设计的window及frame管理器. 这个管理器可以让你快速调整你的Emacs成你想要的样子.
最终,这些window及frame配置信息可以被保存起来并且可以有链接指向这些配置信息,这样你就能够为不同任务分配一个样式,然后按下一个按钮就立即切换到成那个样式(类似于整合了Hyperbole其他功能的Workspace).

Org-mode无法管理库(library)的信息.
Hyperbole能够整理,连接,搜索以及访问文本文件中的库.

Hyperbole还有加速代码浏览以及修改结构化的代码的功能. 并且还支持像Control和Meta那样使用鼠标,这样你就能很方便的操作屏幕上的东西了.

不知道这些有没有回答到你的问题?

如果你想了解的更多,那就好好坐下来阅读一下manual吧. 会很有帮助的.

Bob
