#+TITLE: 使用Org-mode代替delicious(书签管理)
#+URL: https://lists.gnu.org/archive/html/emacs-orgmode/2012-06/msg00640.html
#+AUTHOR: lujun9972
#+CATEGORY: org-mode
#+DATE: [2016-06-18 六 23:21]
#+OPTIONS: ^:{}

作为 =delicious.com= 的长期用户, 我曾经很喜欢Yahoo!转给«sunset»之前的那个旧delicious:当时它能在存储书签时为书签标记tag(并且具有一堆tag补全机制),有很好的浏览器插件, 有能用的Android客户端, 提供了tag管理功能.(重命名,合并,删除tag), 具有很好的搜索功能, 可以为整个tag组或某几个tag下的书签发布RSS feeds.

借助于 Memacs[fn:4] (RSS module),我能使用Org-Mode实现类似的书签管理功能.

从去年开始,delicious提供了一堆我根本不需要也不想要的功能. 更糟糕的是,它还暂停/改变了我常用的很多功能. 同时性能也有所下降.

在我转到它的直接竞争对手(例如http://diigo.com) 那之前,我在想Org-Mode是否能提供一个可用的解决方案. 目前看来,该解决方案有一个明显的劣势那就是无法发布RSS feeds(at least out-of-the-box).但同时,该方案也有它的优势: 完全的本机服务,不依赖于某个网络公司的商务策略,与我的Org-mode完全整合, one (external) technology less to worry about.

-> 真的有人觉得用Org-mode来进行书签管理能够与delicious相媲美吗?

不可否认,确实有一大帮人只是用bookmarks.org或其他类似网站来存储URL而已. 但是我想要的刻不仅仅是这样而已哦:-)

我的需求和解决方案如下:


* 存储浏览器种的书签(我用chrome)

org-protocol.el[fn:1] 看起来蛮有前途的,也[fn:2]蛮有趣的. 可惜它尚不能很方便的添加标签: 我需要先将URL发送到Emacs Org-mode,然后切换到Emacs,跳转到最近添加的那条记录,进入tagging mode,然后才能添加标签(Org-mode具有标签补全功能), 最后还要退出 tagging mode. 这意味着目前的解决方案要多出很多额外的步骤.

我很不喜欢这些额外的步骤.


* 在Android上存储书签

Android版的Mobile-org[fn:3] 很牛逼,但是它的分享/捕获机制也没有很好的支持打标签的功能. 尤其崩溃的居然是缺少标签补全功能.

目前看来,似乎没有什么很好的替代品可以替代delicious Android应用.


* 标签管理(重命名,合并与删除)

我得承认我添加了很多的标签,有时也要使用给予标签的搜索与查询. 但是就目前看来,管理tag并不是什么问题,因为Emacs原生就支持正则查找与替换等功能.

该功能没什么问题.


* 搜索书签

普通的搜索,给予sparse tree的搜索,正则搜索...,Emacs/Org-mode在这方面要好太多了.


* 发布RSS; Social Web Methods

也许以后能够基于Org-mode导出RSS feed, 也可以编写一个外部脚步来解析Org-mode种的CREATED属性并抽取出最近的20个记录来生成feed. 使用Python来写的话,应该不会太难.

虽然我真的很喜欢delicious的这个功能,但是我想没有该功能应该也OK.


* 其他

还有其他书签管理方面有趣的功能我没有提到吗?

* Footnotes


[fn:1] http://orgmode.org/worg/org-contrib/org-protocol.html

[fn:2] http://orgmode.org/worg/org-contrib/org-annotation-helper.html

[fn:3] https://github.com/matburt/mobileorg-android/wiki/ 

[fn:4] https://github.com/novoid/Memacs

